// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

/**
 * Protobuf type {@code signal.AccessControl}
 */
public  final class AccessControl extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:signal.AccessControl)
    AccessControlOrBuilder {
  // Use AccessControl.newBuilder() to construct.
  private AccessControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccessControl() {
    attributes_ = 0;
    members_ = 0;
    addFromInviteLink_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AccessControl(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            attributes_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            members_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            addFromInviteLink_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_AccessControl_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_AccessControl_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.signal.storageservice.storage.protos.groups.AccessControl.class, org.signal.storageservice.storage.protos.groups.AccessControl.Builder.class);
  }

  /**
   * Protobuf enum {@code signal.AccessControl.AccessRequired}
   */
  public enum AccessRequired
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>ANY = 1;</code>
     */
    ANY(1),
    /**
     * <code>MEMBER = 2;</code>
     */
    MEMBER(2),
    /**
     * <code>ADMINISTRATOR = 3;</code>
     */
    ADMINISTRATOR(3),
    /**
     * <code>UNSATISFIABLE = 4;</code>
     */
    UNSATISFIABLE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>ANY = 1;</code>
     */
    public static final int ANY_VALUE = 1;
    /**
     * <code>MEMBER = 2;</code>
     */
    public static final int MEMBER_VALUE = 2;
    /**
     * <code>ADMINISTRATOR = 3;</code>
     */
    public static final int ADMINISTRATOR_VALUE = 3;
    /**
     * <code>UNSATISFIABLE = 4;</code>
     */
    public static final int UNSATISFIABLE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AccessRequired valueOf(int value) {
      return forNumber(value);
    }

    public static AccessRequired forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return ANY;
        case 2: return MEMBER;
        case 3: return ADMINISTRATOR;
        case 4: return UNSATISFIABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccessRequired>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AccessRequired> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccessRequired>() {
            public AccessRequired findValueByNumber(int number) {
              return AccessRequired.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.signal.storageservice.storage.protos.groups.AccessControl.getDescriptor().getEnumTypes().get(0);
    }

    private static final AccessRequired[] VALUES = values();

    public static AccessRequired valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AccessRequired(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:signal.AccessControl.AccessRequired)
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 1;
  private int attributes_;
  /**
   * <code>optional .signal.AccessControl.AccessRequired attributes = 1;</code>
   */
  public int getAttributesValue() {
    return attributes_;
  }
  /**
   * <code>optional .signal.AccessControl.AccessRequired attributes = 1;</code>
   */
  public org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired getAttributes() {
    org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired result = org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.valueOf(attributes_);
    return result == null ? org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNRECOGNIZED : result;
  }

  public static final int MEMBERS_FIELD_NUMBER = 2;
  private int members_;
  /**
   * <code>optional .signal.AccessControl.AccessRequired members = 2;</code>
   */
  public int getMembersValue() {
    return members_;
  }
  /**
   * <code>optional .signal.AccessControl.AccessRequired members = 2;</code>
   */
  public org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired getMembers() {
    org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired result = org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.valueOf(members_);
    return result == null ? org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNRECOGNIZED : result;
  }

  public static final int ADDFROMINVITELINK_FIELD_NUMBER = 3;
  private int addFromInviteLink_;
  /**
   * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 3;</code>
   */
  public int getAddFromInviteLinkValue() {
    return addFromInviteLink_;
  }
  /**
   * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 3;</code>
   */
  public org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired getAddFromInviteLink() {
    org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired result = org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.valueOf(addFromInviteLink_);
    return result == null ? org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (attributes_ != org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      output.writeEnum(1, attributes_);
    }
    if (members_ != org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      output.writeEnum(2, members_);
    }
    if (addFromInviteLink_ != org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      output.writeEnum(3, addFromInviteLink_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (attributes_ != org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, attributes_);
    }
    if (members_ != org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, members_);
    }
    if (addFromInviteLink_ != org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, addFromInviteLink_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.signal.storageservice.storage.protos.groups.AccessControl)) {
      return super.equals(obj);
    }
    org.signal.storageservice.storage.protos.groups.AccessControl other = (org.signal.storageservice.storage.protos.groups.AccessControl) obj;

    boolean result = true;
    result = result && attributes_ == other.attributes_;
    result = result && members_ == other.members_;
    result = result && addFromInviteLink_ == other.addFromInviteLink_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
    hash = (53 * hash) + attributes_;
    hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
    hash = (53 * hash) + members_;
    hash = (37 * hash) + ADDFROMINVITELINK_FIELD_NUMBER;
    hash = (53 * hash) + addFromInviteLink_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.signal.storageservice.storage.protos.groups.AccessControl parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.AccessControl parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.signal.storageservice.storage.protos.groups.AccessControl prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code signal.AccessControl}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:signal.AccessControl)
      org.signal.storageservice.storage.protos.groups.AccessControlOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_AccessControl_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_AccessControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.signal.storageservice.storage.protos.groups.AccessControl.class, org.signal.storageservice.storage.protos.groups.AccessControl.Builder.class);
    }

    // Construct using org.signal.storageservice.storage.protos.groups.AccessControl.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      attributes_ = 0;

      members_ = 0;

      addFromInviteLink_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_AccessControl_descriptor;
    }

    public org.signal.storageservice.storage.protos.groups.AccessControl getDefaultInstanceForType() {
      return org.signal.storageservice.storage.protos.groups.AccessControl.getDefaultInstance();
    }

    public org.signal.storageservice.storage.protos.groups.AccessControl build() {
      org.signal.storageservice.storage.protos.groups.AccessControl result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.signal.storageservice.storage.protos.groups.AccessControl buildPartial() {
      org.signal.storageservice.storage.protos.groups.AccessControl result = new org.signal.storageservice.storage.protos.groups.AccessControl(this);
      result.attributes_ = attributes_;
      result.members_ = members_;
      result.addFromInviteLink_ = addFromInviteLink_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.signal.storageservice.storage.protos.groups.AccessControl) {
        return mergeFrom((org.signal.storageservice.storage.protos.groups.AccessControl)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.signal.storageservice.storage.protos.groups.AccessControl other) {
      if (other == org.signal.storageservice.storage.protos.groups.AccessControl.getDefaultInstance()) return this;
      if (other.attributes_ != 0) {
        setAttributesValue(other.getAttributesValue());
      }
      if (other.members_ != 0) {
        setMembersValue(other.getMembersValue());
      }
      if (other.addFromInviteLink_ != 0) {
        setAddFromInviteLinkValue(other.getAddFromInviteLinkValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.signal.storageservice.storage.protos.groups.AccessControl parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.signal.storageservice.storage.protos.groups.AccessControl) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int attributes_ = 0;
    /**
     * <code>optional .signal.AccessControl.AccessRequired attributes = 1;</code>
     */
    public int getAttributesValue() {
      return attributes_;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired attributes = 1;</code>
     */
    public Builder setAttributesValue(int value) {
      attributes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired attributes = 1;</code>
     */
    public org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired getAttributes() {
      org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired result = org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.valueOf(attributes_);
      return result == null ? org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired attributes = 1;</code>
     */
    public Builder setAttributes(org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired value) {
      if (value == null) {
        throw new NullPointerException();
      }

      attributes_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired attributes = 1;</code>
     */
    public Builder clearAttributes() {

      attributes_ = 0;
      onChanged();
      return this;
    }

    private int members_ = 0;
    /**
     * <code>optional .signal.AccessControl.AccessRequired members = 2;</code>
     */
    public int getMembersValue() {
      return members_;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired members = 2;</code>
     */
    public Builder setMembersValue(int value) {
      members_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired members = 2;</code>
     */
    public org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired getMembers() {
      org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired result = org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.valueOf(members_);
      return result == null ? org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired members = 2;</code>
     */
    public Builder setMembers(org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired value) {
      if (value == null) {
        throw new NullPointerException();
      }

      members_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired members = 2;</code>
     */
    public Builder clearMembers() {

      members_ = 0;
      onChanged();
      return this;
    }

    private int addFromInviteLink_ = 0;
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 3;</code>
     */
    public int getAddFromInviteLinkValue() {
      return addFromInviteLink_;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 3;</code>
     */
    public Builder setAddFromInviteLinkValue(int value) {
      addFromInviteLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 3;</code>
     */
    public org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired getAddFromInviteLink() {
      org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired result = org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.valueOf(addFromInviteLink_);
      return result == null ? org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 3;</code>
     */
    public Builder setAddFromInviteLink(org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired value) {
      if (value == null) {
        throw new NullPointerException();
      }

      addFromInviteLink_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 3;</code>
     */
    public Builder clearAddFromInviteLink() {

      addFromInviteLink_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:signal.AccessControl)
  }

  // @@protoc_insertion_point(class_scope:signal.AccessControl)
  private static final org.signal.storageservice.storage.protos.groups.AccessControl DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.signal.storageservice.storage.protos.groups.AccessControl();
  }

  public static org.signal.storageservice.storage.protos.groups.AccessControl getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccessControl>
      PARSER = new com.google.protobuf.AbstractParser<AccessControl>() {
    public AccessControl parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccessControl(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccessControl> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccessControl> getParserForType() {
    return PARSER;
  }

  public org.signal.storageservice.storage.protos.groups.AccessControl getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

