// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

public interface AvatarUploadAttributesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signal.AvatarUploadAttributes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>optional string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string credential = 2;</code>
   */
  java.lang.String getCredential();
  /**
   * <code>optional string credential = 2;</code>
   */
  com.google.protobuf.ByteString
      getCredentialBytes();

  /**
   * <code>optional string acl = 3;</code>
   */
  java.lang.String getAcl();
  /**
   * <code>optional string acl = 3;</code>
   */
  com.google.protobuf.ByteString
      getAclBytes();

  /**
   * <code>optional string algorithm = 4;</code>
   */
  java.lang.String getAlgorithm();
  /**
   * <code>optional string algorithm = 4;</code>
   */
  com.google.protobuf.ByteString
      getAlgorithmBytes();

  /**
   * <code>optional string date = 5;</code>
   */
  java.lang.String getDate();
  /**
   * <code>optional string date = 5;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>optional string policy = 6;</code>
   */
  java.lang.String getPolicy();
  /**
   * <code>optional string policy = 6;</code>
   */
  com.google.protobuf.ByteString
      getPolicyBytes();

  /**
   * <code>optional string signature = 7;</code>
   */
  java.lang.String getSignature();
  /**
   * <code>optional string signature = 7;</code>
   */
  com.google.protobuf.ByteString
      getSignatureBytes();
}
