// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

public interface ExternalGroupCredentialOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signal.ExternalGroupCredential)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
