// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

/**
 * Protobuf type {@code signal.GroupJoinInfo}
 */
public  final class GroupJoinInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:signal.GroupJoinInfo)
    GroupJoinInfoOrBuilder {
  // Use GroupJoinInfo.newBuilder() to construct.
  private GroupJoinInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupJoinInfo() {
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
    title_ = com.google.protobuf.ByteString.EMPTY;
    avatar_ = "";
    memberCount_ = 0;
    addFromInviteLink_ = 0;
    version_ = 0;
    pendingAdminApproval_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GroupJoinInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            publicKey_ = input.readBytes();
            break;
          }
          case 18: {

            title_ = input.readBytes();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            avatar_ = s;
            break;
          }
          case 32: {

            memberCount_ = input.readUInt32();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            addFromInviteLink_ = rawValue;
            break;
          }
          case 48: {

            version_ = input.readUInt32();
            break;
          }
          case 56: {

            pendingAdminApproval_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_GroupJoinInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_GroupJoinInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.signal.storageservice.storage.protos.groups.GroupJoinInfo.class, org.signal.storageservice.storage.protos.groups.GroupJoinInfo.Builder.class);
  }

  public static final int PUBLICKEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <code>optional bytes publicKey = 1;</code>
   */
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString title_;
  /**
   * <code>optional bytes title = 2;</code>
   */
  public com.google.protobuf.ByteString getTitle() {
    return title_;
  }

  public static final int AVATAR_FIELD_NUMBER = 3;
  private volatile java.lang.Object avatar_;
  /**
   * <code>optional string avatar = 3;</code>
   */
  public java.lang.String getAvatar() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <code>optional string avatar = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMBERCOUNT_FIELD_NUMBER = 4;
  private int memberCount_;
  /**
   * <code>optional uint32 memberCount = 4;</code>
   */
  public int getMemberCount() {
    return memberCount_;
  }

  public static final int ADDFROMINVITELINK_FIELD_NUMBER = 5;
  private int addFromInviteLink_;
  /**
   * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 5;</code>
   */
  public int getAddFromInviteLinkValue() {
    return addFromInviteLink_;
  }
  /**
   * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 5;</code>
   */
  public org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired getAddFromInviteLink() {
    org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired result = org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.valueOf(addFromInviteLink_);
    return result == null ? org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNRECOGNIZED : result;
  }

  public static final int VERSION_FIELD_NUMBER = 6;
  private int version_;
  /**
   * <code>optional uint32 version = 6;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int PENDINGADMINAPPROVAL_FIELD_NUMBER = 7;
  private boolean pendingAdminApproval_;
  /**
   * <code>optional bool pendingAdminApproval = 7;</code>
   */
  public boolean getPendingAdminApproval() {
    return pendingAdminApproval_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!publicKey_.isEmpty()) {
      output.writeBytes(1, publicKey_);
    }
    if (!title_.isEmpty()) {
      output.writeBytes(2, title_);
    }
    if (!getAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
    }
    if (memberCount_ != 0) {
      output.writeUInt32(4, memberCount_);
    }
    if (addFromInviteLink_ != org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      output.writeEnum(5, addFromInviteLink_);
    }
    if (version_ != 0) {
      output.writeUInt32(6, version_);
    }
    if (pendingAdminApproval_ != false) {
      output.writeBool(7, pendingAdminApproval_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!publicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, publicKey_);
    }
    if (!title_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, title_);
    }
    if (!getAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
    }
    if (memberCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, memberCount_);
    }
    if (addFromInviteLink_ != org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, addFromInviteLink_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, version_);
    }
    if (pendingAdminApproval_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, pendingAdminApproval_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.signal.storageservice.storage.protos.groups.GroupJoinInfo)) {
      return super.equals(obj);
    }
    org.signal.storageservice.storage.protos.groups.GroupJoinInfo other = (org.signal.storageservice.storage.protos.groups.GroupJoinInfo) obj;

    boolean result = true;
    result = result && getPublicKey()
        .equals(other.getPublicKey());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getAvatar()
        .equals(other.getAvatar());
    result = result && (getMemberCount()
        == other.getMemberCount());
    result = result && addFromInviteLink_ == other.addFromInviteLink_;
    result = result && (getVersion()
        == other.getVersion());
    result = result && (getPendingAdminApproval()
        == other.getPendingAdminApproval());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPublicKey().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + MEMBERCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getMemberCount();
    hash = (37 * hash) + ADDFROMINVITELINK_FIELD_NUMBER;
    hash = (53 * hash) + addFromInviteLink_;
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + PENDINGADMINAPPROVAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPendingAdminApproval());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.signal.storageservice.storage.protos.groups.GroupJoinInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code signal.GroupJoinInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:signal.GroupJoinInfo)
      org.signal.storageservice.storage.protos.groups.GroupJoinInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_GroupJoinInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_GroupJoinInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.signal.storageservice.storage.protos.groups.GroupJoinInfo.class, org.signal.storageservice.storage.protos.groups.GroupJoinInfo.Builder.class);
    }

    // Construct using org.signal.storageservice.storage.protos.groups.GroupJoinInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      publicKey_ = com.google.protobuf.ByteString.EMPTY;

      title_ = com.google.protobuf.ByteString.EMPTY;

      avatar_ = "";

      memberCount_ = 0;

      addFromInviteLink_ = 0;

      version_ = 0;

      pendingAdminApproval_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_GroupJoinInfo_descriptor;
    }

    public org.signal.storageservice.storage.protos.groups.GroupJoinInfo getDefaultInstanceForType() {
      return org.signal.storageservice.storage.protos.groups.GroupJoinInfo.getDefaultInstance();
    }

    public org.signal.storageservice.storage.protos.groups.GroupJoinInfo build() {
      org.signal.storageservice.storage.protos.groups.GroupJoinInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.signal.storageservice.storage.protos.groups.GroupJoinInfo buildPartial() {
      org.signal.storageservice.storage.protos.groups.GroupJoinInfo result = new org.signal.storageservice.storage.protos.groups.GroupJoinInfo(this);
      result.publicKey_ = publicKey_;
      result.title_ = title_;
      result.avatar_ = avatar_;
      result.memberCount_ = memberCount_;
      result.addFromInviteLink_ = addFromInviteLink_;
      result.version_ = version_;
      result.pendingAdminApproval_ = pendingAdminApproval_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.signal.storageservice.storage.protos.groups.GroupJoinInfo) {
        return mergeFrom((org.signal.storageservice.storage.protos.groups.GroupJoinInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.signal.storageservice.storage.protos.groups.GroupJoinInfo other) {
      if (other == org.signal.storageservice.storage.protos.groups.GroupJoinInfo.getDefaultInstance()) return this;
      if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
        setPublicKey(other.getPublicKey());
      }
      if (other.getTitle() != com.google.protobuf.ByteString.EMPTY) {
        setTitle(other.getTitle());
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        onChanged();
      }
      if (other.getMemberCount() != 0) {
        setMemberCount(other.getMemberCount());
      }
      if (other.addFromInviteLink_ != 0) {
        setAddFromInviteLinkValue(other.getAddFromInviteLinkValue());
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getPendingAdminApproval() != false) {
        setPendingAdminApproval(other.getPendingAdminApproval());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.signal.storageservice.storage.protos.groups.GroupJoinInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.signal.storageservice.storage.protos.groups.GroupJoinInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      publicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public Builder clearPublicKey() {

      publicKey_ = getDefaultInstance().getPublicKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString title_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes title = 2;</code>
     */
    public com.google.protobuf.ByteString getTitle() {
      return title_;
    }
    /**
     * <code>optional bytes title = 2;</code>
     */
    public Builder setTitle(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes title = 2;</code>
     */
    public Builder clearTitle() {

      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }

    private java.lang.Object avatar_ = "";
    /**
     * <code>optional string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string avatar = 3;</code>
     */
    public Builder setAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      avatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string avatar = 3;</code>
     */
    public Builder clearAvatar() {

      avatar_ = getDefaultInstance().getAvatar();
      onChanged();
      return this;
    }
    /**
     * <code>optional string avatar = 3;</code>
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      avatar_ = value;
      onChanged();
      return this;
    }

    private int memberCount_ ;
    /**
     * <code>optional uint32 memberCount = 4;</code>
     */
    public int getMemberCount() {
      return memberCount_;
    }
    /**
     * <code>optional uint32 memberCount = 4;</code>
     */
    public Builder setMemberCount(int value) {

      memberCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 memberCount = 4;</code>
     */
    public Builder clearMemberCount() {

      memberCount_ = 0;
      onChanged();
      return this;
    }

    private int addFromInviteLink_ = 0;
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 5;</code>
     */
    public int getAddFromInviteLinkValue() {
      return addFromInviteLink_;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 5;</code>
     */
    public Builder setAddFromInviteLinkValue(int value) {
      addFromInviteLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 5;</code>
     */
    public org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired getAddFromInviteLink() {
      org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired result = org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.valueOf(addFromInviteLink_);
      return result == null ? org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 5;</code>
     */
    public Builder setAddFromInviteLink(org.signal.storageservice.storage.protos.groups.AccessControl.AccessRequired value) {
      if (value == null) {
        throw new NullPointerException();
      }

      addFromInviteLink_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.AccessControl.AccessRequired addFromInviteLink = 5;</code>
     */
    public Builder clearAddFromInviteLink() {

      addFromInviteLink_ = 0;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>optional uint32 version = 6;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional uint32 version = 6;</code>
     */
    public Builder setVersion(int value) {

      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 version = 6;</code>
     */
    public Builder clearVersion() {

      version_ = 0;
      onChanged();
      return this;
    }

    private boolean pendingAdminApproval_ ;
    /**
     * <code>optional bool pendingAdminApproval = 7;</code>
     */
    public boolean getPendingAdminApproval() {
      return pendingAdminApproval_;
    }
    /**
     * <code>optional bool pendingAdminApproval = 7;</code>
     */
    public Builder setPendingAdminApproval(boolean value) {

      pendingAdminApproval_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool pendingAdminApproval = 7;</code>
     */
    public Builder clearPendingAdminApproval() {

      pendingAdminApproval_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:signal.GroupJoinInfo)
  }

  // @@protoc_insertion_point(class_scope:signal.GroupJoinInfo)
  private static final org.signal.storageservice.storage.protos.groups.GroupJoinInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.signal.storageservice.storage.protos.groups.GroupJoinInfo();
  }

  public static org.signal.storageservice.storage.protos.groups.GroupJoinInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupJoinInfo>
      PARSER = new com.google.protobuf.AbstractParser<GroupJoinInfo>() {
    public GroupJoinInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupJoinInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GroupJoinInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GroupJoinInfo> getParserForType() {
    return PARSER;
  }

  public org.signal.storageservice.storage.protos.groups.GroupJoinInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

