// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

public final class GroupProtos {
  private GroupProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_AvatarUploadAttributes_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_AvatarUploadAttributes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_Member_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_Member_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_MemberPendingProfileKey_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_MemberPendingProfileKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_MemberPendingAdminApproval_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_MemberPendingAdminApproval_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_AccessControl_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_AccessControl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_Group_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupJoinInfo_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupJoinInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_AddMemberAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_AddMemberAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_DeleteMemberAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_DeleteMemberAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyMemberRoleAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyMemberRoleAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyMemberProfileKeyAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyMemberProfileKeyAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_AddMemberPendingProfileKeyAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_AddMemberPendingProfileKeyAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_DeleteMemberPendingProfileKeyAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_DeleteMemberPendingProfileKeyAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_PromoteMemberPendingProfileKeyAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_PromoteMemberPendingProfileKeyAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_AddMemberPendingAdminApprovalAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_AddMemberPendingAdminApprovalAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_DeleteMemberPendingAdminApprovalAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_DeleteMemberPendingAdminApprovalAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_PromoteMemberPendingAdminApprovalAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_PromoteMemberPendingAdminApprovalAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyTitleAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyTitleAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyAvatarAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyAvatarAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyDisappearingMessageTimerAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyDisappearingMessageTimerAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyAttributesAccessControlAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyAttributesAccessControlAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyMembersAccessControlAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyMembersAccessControlAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChange_Actions_ModifyInviteLinkPasswordAction_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChange_Actions_ModifyInviteLinkPasswordAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChanges_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChanges_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_GroupChanges_GroupChangeState_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_GroupChanges_GroupChangeState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_ExternalGroupCredential_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signal_ExternalGroupCredential_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Groups.proto\022\006signal\"\212\001\n\026AvatarUploadA" +
      "ttributes\022\013\n\003key\030\001 \001(\t\022\022\n\ncredential\030\002 \001" +
      "(\t\022\013\n\003acl\030\003 \001(\t\022\021\n\talgorithm\030\004 \001(\t\022\014\n\004da" +
      "te\030\005 \001(\t\022\016\n\006policy\030\006 \001(\t\022\021\n\tsignature\030\007 " +
      "\001(\t\"\263\001\n\006Member\022\016\n\006userId\030\001 \001(\014\022!\n\004role\030\002" +
      " \001(\0162\023.signal.Member.Role\022\022\n\nprofileKey\030" +
      "\003 \001(\014\022\024\n\014presentation\030\004 \001(\014\022\027\n\017joinedAtV" +
      "ersion\030\005 \001(\r\"3\n\004Role\022\013\n\007UNKNOWN\020\000\022\013\n\007DEF" +
      "AULT\020\001\022\021\n\rADMINISTRATOR\020\002\"c\n\027MemberPendi" +
      "ngProfileKey\022\036\n\006member\030\001 \001(\0132\016.signal.Me",
      "mber\022\025\n\raddedByUserId\030\002 \001(\014\022\021\n\ttimestamp" +
      "\030\003 \001(\004\"i\n\032MemberPendingAdminApproval\022\016\n\006" +
      "userId\030\001 \001(\014\022\022\n\nprofileKey\030\002 \001(\014\022\024\n\014pres" +
      "entation\030\003 \001(\014\022\021\n\ttimestamp\030\004 \001(\004\"\233\002\n\rAc" +
      "cessControl\0228\n\nattributes\030\001 \001(\0162$.signal" +
      ".AccessControl.AccessRequired\0225\n\007members" +
      "\030\002 \001(\0162$.signal.AccessControl.AccessRequ" +
      "ired\022?\n\021addFromInviteLink\030\003 \001(\0162$.signal" +
      ".AccessControl.AccessRequired\"X\n\016AccessR" +
      "equired\022\013\n\007UNKNOWN\020\000\022\007\n\003ANY\020\001\022\n\n\006MEMBER\020",
      "\002\022\021\n\rADMINISTRATOR\020\003\022\021\n\rUNSATISFIABLE\020\004\"" +
      "\344\002\n\005Group\022\021\n\tpublicKey\030\001 \001(\014\022\r\n\005title\030\002 " +
      "\001(\014\022\016\n\006avatar\030\003 \001(\t\022!\n\031disappearingMessa" +
      "gesTimer\030\004 \001(\014\022,\n\raccessControl\030\005 \001(\0132\025." +
      "signal.AccessControl\022\017\n\007version\030\006 \001(\r\022\037\n" +
      "\007members\030\007 \003(\0132\016.signal.Member\022A\n\030member" +
      "sPendingProfileKey\030\010 \003(\0132\037.signal.Member" +
      "PendingProfileKey\022G\n\033membersPendingAdmin" +
      "Approval\030\t \003(\0132\".signal.MemberPendingAdm" +
      "inApproval\022\032\n\022inviteLinkPassword\030\n \001(\014\"\306",
      "\001\n\rGroupJoinInfo\022\021\n\tpublicKey\030\001 \001(\014\022\r\n\005t" +
      "itle\030\002 \001(\014\022\016\n\006avatar\030\003 \001(\t\022\023\n\013memberCoun" +
      "t\030\004 \001(\r\022?\n\021addFromInviteLink\030\005 \001(\0162$.sig" +
      "nal.AccessControl.AccessRequired\022\017\n\007vers" +
      "ion\030\006 \001(\r\022\034\n\024pendingAdminApproval\030\007 \001(\010\"" +
      "\356\026\n\013GroupChange\022\017\n\007actions\030\001 \001(\014\022\027\n\017serv" +
      "erSignature\030\002 \001(\014\022\023\n\013changeEpoch\030\003 \001(\r\032\237" +
      "\026\n\007Actions\022\022\n\nsourceUuid\030\001 \001(\014\022\017\n\007versio" +
      "n\030\002 \001(\r\022?\n\naddMembers\030\003 \003(\0132+.signal.Gro" +
      "upChange.Actions.AddMemberAction\022E\n\rdele",
      "teMembers\030\004 \003(\0132..signal.GroupChange.Act" +
      "ions.DeleteMemberAction\022M\n\021modifyMemberR" +
      "oles\030\005 \003(\01322.signal.GroupChange.Actions." +
      "ModifyMemberRoleAction\022Y\n\027modifyMemberPr" +
      "ofileKeys\030\006 \003(\01328.signal.GroupChange.Act" +
      "ions.ModifyMemberProfileKeyAction\022a\n\033add" +
      "MembersPendingProfileKey\030\007 \003(\0132<.signal." +
      "GroupChange.Actions.AddMemberPendingProf" +
      "ileKeyAction\022g\n\036deleteMembersPendingProf" +
      "ileKey\030\010 \003(\0132?.signal.GroupChange.Action",
      "s.DeleteMemberPendingProfileKeyAction\022i\n" +
      "\037promoteMembersPendingProfileKey\030\t \003(\0132@" +
      ".signal.GroupChange.Actions.PromoteMembe" +
      "rPendingProfileKeyAction\022B\n\013modifyTitle\030" +
      "\n \001(\0132-.signal.GroupChange.Actions.Modif" +
      "yTitleAction\022D\n\014modifyAvatar\030\013 \001(\0132..sig" +
      "nal.GroupChange.Actions.ModifyAvatarActi" +
      "on\022h\n\036modifyDisappearingMessageTimer\030\014 \001" +
      "(\0132@.signal.GroupChange.Actions.ModifyDi" +
      "sappearingMessageTimerAction\022_\n\026modifyAt",
      "tributesAccess\030\r \001(\0132?.signal.GroupChang" +
      "e.Actions.ModifyAttributesAccessControlA" +
      "ction\022X\n\022modifyMemberAccess\030\016 \001(\0132<.sign" +
      "al.GroupChange.Actions.ModifyMembersAcce" +
      "ssControlAction\022m\n\035modifyAddFromInviteLi" +
      "nkAccess\030\017 \001(\0132F.signal.GroupChange.Acti" +
      "ons.ModifyAddFromInviteLinkAccessControl" +
      "Action\022g\n\036addMembersPendingAdminApproval" +
      "\030\020 \003(\0132?.signal.GroupChange.Actions.AddM" +
      "emberPendingAdminApprovalAction\022m\n!delet",
      "eMembersPendingAdminApproval\030\021 \003(\0132B.sig" +
      "nal.GroupChange.Actions.DeleteMemberPend" +
      "ingAdminApprovalAction\022o\n\"promoteMembers" +
      "PendingAdminApproval\030\022 \003(\0132C.signal.Grou" +
      "pChange.Actions.PromoteMemberPendingAdmi" +
      "nApprovalAction\022\\\n\030modifyInviteLinkPassw" +
      "ord\030\023 \001(\0132:.signal.GroupChange.Actions.M" +
      "odifyInviteLinkPasswordAction\032L\n\017AddMemb" +
      "erAction\022\035\n\005added\030\001 \001(\0132\016.signal.Member\022" +
      "\032\n\022joinFromInviteLink\030\002 \001(\010\032+\n\022DeleteMem",
      "berAction\022\025\n\rdeletedUserId\030\001 \001(\014\032K\n\026Modi" +
      "fyMemberRoleAction\022\016\n\006userId\030\001 \001(\014\022!\n\004ro" +
      "le\030\002 \001(\0162\023.signal.Member.Role\0324\n\034ModifyM" +
      "emberProfileKeyAction\022\024\n\014presentation\030\001 " +
      "\001(\014\032R\n AddMemberPendingProfileKeyAction\022" +
      ".\n\005added\030\001 \001(\0132\037.signal.MemberPendingPro" +
      "fileKey\032<\n#DeleteMemberPendingProfileKey" +
      "Action\022\025\n\rdeletedUserId\030\001 \001(\014\032<\n$Promote" +
      "MemberPendingProfileKeyAction\022\024\n\014present" +
      "ation\030\001 \001(\014\032X\n#AddMemberPendingAdminAppr",
      "ovalAction\0221\n\005added\030\001 \001(\0132\".signal.Membe" +
      "rPendingAdminApproval\032?\n&DeleteMemberPen" +
      "dingAdminApprovalAction\022\025\n\rdeletedUserId" +
      "\030\001 \001(\014\032\\\n\'PromoteMemberPendingAdminAppro" +
      "valAction\022\016\n\006userId\030\001 \001(\014\022!\n\004role\030\002 \001(\0162" +
      "\023.signal.Member.Role\032\"\n\021ModifyTitleActio" +
      "n\022\r\n\005title\030\001 \001(\014\032$\n\022ModifyAvatarAction\022\016" +
      "\n\006avatar\030\001 \001(\t\0325\n$ModifyDisappearingMess" +
      "ageTimerAction\022\r\n\005timer\030\001 \001(\014\032e\n#ModifyA" +
      "ttributesAccessControlAction\022>\n\020attribut",
      "esAccess\030\001 \001(\0162$.signal.AccessControl.Ac" +
      "cessRequired\032_\n ModifyMembersAccessContr" +
      "olAction\022;\n\rmembersAccess\030\001 \001(\0162$.signal" +
      ".AccessControl.AccessRequired\032s\n*ModifyA" +
      "ddFromInviteLinkAccessControlAction\022E\n\027a" +
      "ddFromInviteLinkAccess\030\001 \001(\0162$.signal.Ac" +
      "cessControl.AccessRequired\032<\n\036ModifyInvi" +
      "teLinkPasswordAction\022\032\n\022inviteLinkPasswo" +
      "rd\030\001 \001(\014\"\254\001\n\014GroupChanges\022;\n\014groupChange" +
      "s\030\001 \003(\0132%.signal.GroupChanges.GroupChang",
      "eState\032_\n\020GroupChangeState\022(\n\013groupChang" +
      "e\030\001 \001(\0132\023.signal.GroupChange\022!\n\ngroupSta" +
      "te\030\002 \001(\0132\r.signal.Group\"(\n\027ExternalGroup" +
      "Credential\022\r\n\005token\030\001 \001(\tB@\n/org.signal." +
      "storageservice.storage.protos.groupsB\013Gr" +
      "oupProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_signal_AvatarUploadAttributes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_signal_AvatarUploadAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_AvatarUploadAttributes_descriptor,
        new java.lang.String[] { "Key", "Credential", "Acl", "Algorithm", "Date", "Policy", "Signature", });
    internal_static_signal_Member_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_signal_Member_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_Member_descriptor,
        new java.lang.String[] { "UserId", "Role", "ProfileKey", "Presentation", "JoinedAtVersion", });
    internal_static_signal_MemberPendingProfileKey_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_signal_MemberPendingProfileKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_MemberPendingProfileKey_descriptor,
        new java.lang.String[] { "Member", "AddedByUserId", "Timestamp", });
    internal_static_signal_MemberPendingAdminApproval_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_signal_MemberPendingAdminApproval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_MemberPendingAdminApproval_descriptor,
        new java.lang.String[] { "UserId", "ProfileKey", "Presentation", "Timestamp", });
    internal_static_signal_AccessControl_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_signal_AccessControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_AccessControl_descriptor,
        new java.lang.String[] { "Attributes", "Members", "AddFromInviteLink", });
    internal_static_signal_Group_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_signal_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_Group_descriptor,
        new java.lang.String[] { "PublicKey", "Title", "Avatar", "DisappearingMessagesTimer", "AccessControl", "Version", "Members", "MembersPendingProfileKey", "MembersPendingAdminApproval", "InviteLinkPassword", });
    internal_static_signal_GroupJoinInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_signal_GroupJoinInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupJoinInfo_descriptor,
        new java.lang.String[] { "PublicKey", "Title", "Avatar", "MemberCount", "AddFromInviteLink", "Version", "PendingAdminApproval", });
    internal_static_signal_GroupChange_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_signal_GroupChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_descriptor,
        new java.lang.String[] { "Actions", "ServerSignature", "ChangeEpoch", });
    internal_static_signal_GroupChange_Actions_descriptor =
      internal_static_signal_GroupChange_descriptor.getNestedTypes().get(0);
    internal_static_signal_GroupChange_Actions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_descriptor,
        new java.lang.String[] { "SourceUuid", "Version", "AddMembers", "DeleteMembers", "ModifyMemberRoles", "ModifyMemberProfileKeys", "AddMembersPendingProfileKey", "DeleteMembersPendingProfileKey", "PromoteMembersPendingProfileKey", "ModifyTitle", "ModifyAvatar", "ModifyDisappearingMessageTimer", "ModifyAttributesAccess", "ModifyMemberAccess", "ModifyAddFromInviteLinkAccess", "AddMembersPendingAdminApproval", "DeleteMembersPendingAdminApproval", "PromoteMembersPendingAdminApproval", "ModifyInviteLinkPassword", });
    internal_static_signal_GroupChange_Actions_AddMemberAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(0);
    internal_static_signal_GroupChange_Actions_AddMemberAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_AddMemberAction_descriptor,
        new java.lang.String[] { "Added", "JoinFromInviteLink", });
    internal_static_signal_GroupChange_Actions_DeleteMemberAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(1);
    internal_static_signal_GroupChange_Actions_DeleteMemberAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_DeleteMemberAction_descriptor,
        new java.lang.String[] { "DeletedUserId", });
    internal_static_signal_GroupChange_Actions_ModifyMemberRoleAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(2);
    internal_static_signal_GroupChange_Actions_ModifyMemberRoleAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyMemberRoleAction_descriptor,
        new java.lang.String[] { "UserId", "Role", });
    internal_static_signal_GroupChange_Actions_ModifyMemberProfileKeyAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(3);
    internal_static_signal_GroupChange_Actions_ModifyMemberProfileKeyAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyMemberProfileKeyAction_descriptor,
        new java.lang.String[] { "Presentation", });
    internal_static_signal_GroupChange_Actions_AddMemberPendingProfileKeyAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(4);
    internal_static_signal_GroupChange_Actions_AddMemberPendingProfileKeyAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_AddMemberPendingProfileKeyAction_descriptor,
        new java.lang.String[] { "Added", });
    internal_static_signal_GroupChange_Actions_DeleteMemberPendingProfileKeyAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(5);
    internal_static_signal_GroupChange_Actions_DeleteMemberPendingProfileKeyAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_DeleteMemberPendingProfileKeyAction_descriptor,
        new java.lang.String[] { "DeletedUserId", });
    internal_static_signal_GroupChange_Actions_PromoteMemberPendingProfileKeyAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(6);
    internal_static_signal_GroupChange_Actions_PromoteMemberPendingProfileKeyAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_PromoteMemberPendingProfileKeyAction_descriptor,
        new java.lang.String[] { "Presentation", });
    internal_static_signal_GroupChange_Actions_AddMemberPendingAdminApprovalAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(7);
    internal_static_signal_GroupChange_Actions_AddMemberPendingAdminApprovalAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_AddMemberPendingAdminApprovalAction_descriptor,
        new java.lang.String[] { "Added", });
    internal_static_signal_GroupChange_Actions_DeleteMemberPendingAdminApprovalAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(8);
    internal_static_signal_GroupChange_Actions_DeleteMemberPendingAdminApprovalAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_DeleteMemberPendingAdminApprovalAction_descriptor,
        new java.lang.String[] { "DeletedUserId", });
    internal_static_signal_GroupChange_Actions_PromoteMemberPendingAdminApprovalAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(9);
    internal_static_signal_GroupChange_Actions_PromoteMemberPendingAdminApprovalAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_PromoteMemberPendingAdminApprovalAction_descriptor,
        new java.lang.String[] { "UserId", "Role", });
    internal_static_signal_GroupChange_Actions_ModifyTitleAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(10);
    internal_static_signal_GroupChange_Actions_ModifyTitleAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyTitleAction_descriptor,
        new java.lang.String[] { "Title", });
    internal_static_signal_GroupChange_Actions_ModifyAvatarAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(11);
    internal_static_signal_GroupChange_Actions_ModifyAvatarAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyAvatarAction_descriptor,
        new java.lang.String[] { "Avatar", });
    internal_static_signal_GroupChange_Actions_ModifyDisappearingMessageTimerAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(12);
    internal_static_signal_GroupChange_Actions_ModifyDisappearingMessageTimerAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyDisappearingMessageTimerAction_descriptor,
        new java.lang.String[] { "Timer", });
    internal_static_signal_GroupChange_Actions_ModifyAttributesAccessControlAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(13);
    internal_static_signal_GroupChange_Actions_ModifyAttributesAccessControlAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyAttributesAccessControlAction_descriptor,
        new java.lang.String[] { "AttributesAccess", });
    internal_static_signal_GroupChange_Actions_ModifyMembersAccessControlAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(14);
    internal_static_signal_GroupChange_Actions_ModifyMembersAccessControlAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyMembersAccessControlAction_descriptor,
        new java.lang.String[] { "MembersAccess", });
    internal_static_signal_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(15);
    internal_static_signal_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyAddFromInviteLinkAccessControlAction_descriptor,
        new java.lang.String[] { "AddFromInviteLinkAccess", });
    internal_static_signal_GroupChange_Actions_ModifyInviteLinkPasswordAction_descriptor =
      internal_static_signal_GroupChange_Actions_descriptor.getNestedTypes().get(16);
    internal_static_signal_GroupChange_Actions_ModifyInviteLinkPasswordAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChange_Actions_ModifyInviteLinkPasswordAction_descriptor,
        new java.lang.String[] { "InviteLinkPassword", });
    internal_static_signal_GroupChanges_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_signal_GroupChanges_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChanges_descriptor,
        new java.lang.String[] { "GroupChanges", });
    internal_static_signal_GroupChanges_GroupChangeState_descriptor =
      internal_static_signal_GroupChanges_descriptor.getNestedTypes().get(0);
    internal_static_signal_GroupChanges_GroupChangeState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_GroupChanges_GroupChangeState_descriptor,
        new java.lang.String[] { "GroupChange", "GroupState", });
    internal_static_signal_ExternalGroupCredential_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_signal_ExternalGroupCredential_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signal_ExternalGroupCredential_descriptor,
        new java.lang.String[] { "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
