// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

/**
 * Protobuf type {@code signal.Group}
 */
public  final class Group extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:signal.Group)
    GroupOrBuilder {
  // Use Group.newBuilder() to construct.
  private Group(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Group() {
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
    title_ = com.google.protobuf.ByteString.EMPTY;
    avatar_ = "";
    disappearingMessagesTimer_ = com.google.protobuf.ByteString.EMPTY;
    version_ = 0;
    members_ = java.util.Collections.emptyList();
    membersPendingProfileKey_ = java.util.Collections.emptyList();
    membersPendingAdminApproval_ = java.util.Collections.emptyList();
    inviteLinkPassword_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Group(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            publicKey_ = input.readBytes();
            break;
          }
          case 18: {

            title_ = input.readBytes();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            avatar_ = s;
            break;
          }
          case 34: {

            disappearingMessagesTimer_ = input.readBytes();
            break;
          }
          case 42: {
            org.signal.storageservice.storage.protos.groups.AccessControl.Builder subBuilder = null;
            if (accessControl_ != null) {
              subBuilder = accessControl_.toBuilder();
            }
            accessControl_ = input.readMessage(org.signal.storageservice.storage.protos.groups.AccessControl.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(accessControl_);
              accessControl_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            version_ = input.readUInt32();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              members_ = new java.util.ArrayList<org.signal.storageservice.storage.protos.groups.Member>();
              mutable_bitField0_ |= 0x00000040;
            }
            members_.add(
                input.readMessage(org.signal.storageservice.storage.protos.groups.Member.parser(), extensionRegistry));
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              membersPendingProfileKey_ = new java.util.ArrayList<org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey>();
              mutable_bitField0_ |= 0x00000080;
            }
            membersPendingProfileKey_.add(
                input.readMessage(org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.parser(), extensionRegistry));
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              membersPendingAdminApproval_ = new java.util.ArrayList<org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval>();
              mutable_bitField0_ |= 0x00000100;
            }
            membersPendingAdminApproval_.add(
                input.readMessage(org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.parser(), extensionRegistry));
            break;
          }
          case 82: {

            inviteLinkPassword_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        members_ = java.util.Collections.unmodifiableList(members_);
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        membersPendingProfileKey_ = java.util.Collections.unmodifiableList(membersPendingProfileKey_);
      }
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        membersPendingAdminApproval_ = java.util.Collections.unmodifiableList(membersPendingAdminApproval_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Group_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Group_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.signal.storageservice.storage.protos.groups.Group.class, org.signal.storageservice.storage.protos.groups.Group.Builder.class);
  }

  private int bitField0_;
  public static final int PUBLICKEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <code>optional bytes publicKey = 1;</code>
   */
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString title_;
  /**
   * <code>optional bytes title = 2;</code>
   */
  public com.google.protobuf.ByteString getTitle() {
    return title_;
  }

  public static final int AVATAR_FIELD_NUMBER = 3;
  private volatile java.lang.Object avatar_;
  /**
   * <code>optional string avatar = 3;</code>
   */
  public java.lang.String getAvatar() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <code>optional string avatar = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISAPPEARINGMESSAGESTIMER_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString disappearingMessagesTimer_;
  /**
   * <code>optional bytes disappearingMessagesTimer = 4;</code>
   */
  public com.google.protobuf.ByteString getDisappearingMessagesTimer() {
    return disappearingMessagesTimer_;
  }

  public static final int ACCESSCONTROL_FIELD_NUMBER = 5;
  private org.signal.storageservice.storage.protos.groups.AccessControl accessControl_;
  /**
   * <code>optional .signal.AccessControl accessControl = 5;</code>
   */
  public boolean hasAccessControl() {
    return accessControl_ != null;
  }
  /**
   * <code>optional .signal.AccessControl accessControl = 5;</code>
   */
  public org.signal.storageservice.storage.protos.groups.AccessControl getAccessControl() {
    return accessControl_ == null ? org.signal.storageservice.storage.protos.groups.AccessControl.getDefaultInstance() : accessControl_;
  }
  /**
   * <code>optional .signal.AccessControl accessControl = 5;</code>
   */
  public org.signal.storageservice.storage.protos.groups.AccessControlOrBuilder getAccessControlOrBuilder() {
    return getAccessControl();
  }

  public static final int VERSION_FIELD_NUMBER = 6;
  private int version_;
  /**
   * <code>optional uint32 version = 6;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int MEMBERS_FIELD_NUMBER = 7;
  private java.util.List<org.signal.storageservice.storage.protos.groups.Member> members_;
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  public java.util.List<org.signal.storageservice.storage.protos.groups.Member> getMembersList() {
    return members_;
  }
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  public java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberOrBuilder>
      getMembersOrBuilderList() {
    return members_;
  }
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  public int getMembersCount() {
    return members_.size();
  }
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  public org.signal.storageservice.storage.protos.groups.Member getMembers(int index) {
    return members_.get(index);
  }
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  public org.signal.storageservice.storage.protos.groups.MemberOrBuilder getMembersOrBuilder(
      int index) {
    return members_.get(index);
  }

  public static final int MEMBERSPENDINGPROFILEKEY_FIELD_NUMBER = 8;
  private java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey> membersPendingProfileKey_;
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  public java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey> getMembersPendingProfileKeyList() {
    return membersPendingProfileKey_;
  }
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  public java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder>
      getMembersPendingProfileKeyOrBuilderList() {
    return membersPendingProfileKey_;
  }
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  public int getMembersPendingProfileKeyCount() {
    return membersPendingProfileKey_.size();
  }
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey getMembersPendingProfileKey(int index) {
    return membersPendingProfileKey_.get(index);
  }
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder getMembersPendingProfileKeyOrBuilder(
      int index) {
    return membersPendingProfileKey_.get(index);
  }

  public static final int MEMBERSPENDINGADMINAPPROVAL_FIELD_NUMBER = 9;
  private java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval> membersPendingAdminApproval_;
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  public java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval> getMembersPendingAdminApprovalList() {
    return membersPendingAdminApproval_;
  }
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  public java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder>
      getMembersPendingAdminApprovalOrBuilderList() {
    return membersPendingAdminApproval_;
  }
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  public int getMembersPendingAdminApprovalCount() {
    return membersPendingAdminApproval_.size();
  }
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval getMembersPendingAdminApproval(int index) {
    return membersPendingAdminApproval_.get(index);
  }
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder getMembersPendingAdminApprovalOrBuilder(
      int index) {
    return membersPendingAdminApproval_.get(index);
  }

  public static final int INVITELINKPASSWORD_FIELD_NUMBER = 10;
  private com.google.protobuf.ByteString inviteLinkPassword_;
  /**
   * <code>optional bytes inviteLinkPassword = 10;</code>
   */
  public com.google.protobuf.ByteString getInviteLinkPassword() {
    return inviteLinkPassword_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!publicKey_.isEmpty()) {
      output.writeBytes(1, publicKey_);
    }
    if (!title_.isEmpty()) {
      output.writeBytes(2, title_);
    }
    if (!getAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
    }
    if (!disappearingMessagesTimer_.isEmpty()) {
      output.writeBytes(4, disappearingMessagesTimer_);
    }
    if (accessControl_ != null) {
      output.writeMessage(5, getAccessControl());
    }
    if (version_ != 0) {
      output.writeUInt32(6, version_);
    }
    for (int i = 0; i < members_.size(); i++) {
      output.writeMessage(7, members_.get(i));
    }
    for (int i = 0; i < membersPendingProfileKey_.size(); i++) {
      output.writeMessage(8, membersPendingProfileKey_.get(i));
    }
    for (int i = 0; i < membersPendingAdminApproval_.size(); i++) {
      output.writeMessage(9, membersPendingAdminApproval_.get(i));
    }
    if (!inviteLinkPassword_.isEmpty()) {
      output.writeBytes(10, inviteLinkPassword_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!publicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, publicKey_);
    }
    if (!title_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, title_);
    }
    if (!getAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
    }
    if (!disappearingMessagesTimer_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, disappearingMessagesTimer_);
    }
    if (accessControl_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAccessControl());
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, version_);
    }
    for (int i = 0; i < members_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, members_.get(i));
    }
    for (int i = 0; i < membersPendingProfileKey_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, membersPendingProfileKey_.get(i));
    }
    for (int i = 0; i < membersPendingAdminApproval_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, membersPendingAdminApproval_.get(i));
    }
    if (!inviteLinkPassword_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, inviteLinkPassword_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.signal.storageservice.storage.protos.groups.Group)) {
      return super.equals(obj);
    }
    org.signal.storageservice.storage.protos.groups.Group other = (org.signal.storageservice.storage.protos.groups.Group) obj;

    boolean result = true;
    result = result && getPublicKey()
        .equals(other.getPublicKey());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getAvatar()
        .equals(other.getAvatar());
    result = result && getDisappearingMessagesTimer()
        .equals(other.getDisappearingMessagesTimer());
    result = result && (hasAccessControl() == other.hasAccessControl());
    if (hasAccessControl()) {
      result = result && getAccessControl()
          .equals(other.getAccessControl());
    }
    result = result && (getVersion()
        == other.getVersion());
    result = result && getMembersList()
        .equals(other.getMembersList());
    result = result && getMembersPendingProfileKeyList()
        .equals(other.getMembersPendingProfileKeyList());
    result = result && getMembersPendingAdminApprovalList()
        .equals(other.getMembersPendingAdminApprovalList());
    result = result && getInviteLinkPassword()
        .equals(other.getInviteLinkPassword());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPublicKey().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + DISAPPEARINGMESSAGESTIMER_FIELD_NUMBER;
    hash = (53 * hash) + getDisappearingMessagesTimer().hashCode();
    if (hasAccessControl()) {
      hash = (37 * hash) + ACCESSCONTROL_FIELD_NUMBER;
      hash = (53 * hash) + getAccessControl().hashCode();
    }
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (getMembersCount() > 0) {
      hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMembersList().hashCode();
    }
    if (getMembersPendingProfileKeyCount() > 0) {
      hash = (37 * hash) + MEMBERSPENDINGPROFILEKEY_FIELD_NUMBER;
      hash = (53 * hash) + getMembersPendingProfileKeyList().hashCode();
    }
    if (getMembersPendingAdminApprovalCount() > 0) {
      hash = (37 * hash) + MEMBERSPENDINGADMINAPPROVAL_FIELD_NUMBER;
      hash = (53 * hash) + getMembersPendingAdminApprovalList().hashCode();
    }
    hash = (37 * hash) + INVITELINKPASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getInviteLinkPassword().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.signal.storageservice.storage.protos.groups.Group parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.Group parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.signal.storageservice.storage.protos.groups.Group prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code signal.Group}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:signal.Group)
      org.signal.storageservice.storage.protos.groups.GroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Group_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Group_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.signal.storageservice.storage.protos.groups.Group.class, org.signal.storageservice.storage.protos.groups.Group.Builder.class);
    }

    // Construct using org.signal.storageservice.storage.protos.groups.Group.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMembersFieldBuilder();
        getMembersPendingProfileKeyFieldBuilder();
        getMembersPendingAdminApprovalFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      publicKey_ = com.google.protobuf.ByteString.EMPTY;

      title_ = com.google.protobuf.ByteString.EMPTY;

      avatar_ = "";

      disappearingMessagesTimer_ = com.google.protobuf.ByteString.EMPTY;

      if (accessControlBuilder_ == null) {
        accessControl_ = null;
      } else {
        accessControl_ = null;
        accessControlBuilder_ = null;
      }
      version_ = 0;

      if (membersBuilder_ == null) {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        membersBuilder_.clear();
      }
      if (membersPendingProfileKeyBuilder_ == null) {
        membersPendingProfileKey_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        membersPendingProfileKeyBuilder_.clear();
      }
      if (membersPendingAdminApprovalBuilder_ == null) {
        membersPendingAdminApproval_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
      } else {
        membersPendingAdminApprovalBuilder_.clear();
      }
      inviteLinkPassword_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Group_descriptor;
    }

    public org.signal.storageservice.storage.protos.groups.Group getDefaultInstanceForType() {
      return org.signal.storageservice.storage.protos.groups.Group.getDefaultInstance();
    }

    public org.signal.storageservice.storage.protos.groups.Group build() {
      org.signal.storageservice.storage.protos.groups.Group result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.signal.storageservice.storage.protos.groups.Group buildPartial() {
      org.signal.storageservice.storage.protos.groups.Group result = new org.signal.storageservice.storage.protos.groups.Group(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.publicKey_ = publicKey_;
      result.title_ = title_;
      result.avatar_ = avatar_;
      result.disappearingMessagesTimer_ = disappearingMessagesTimer_;
      if (accessControlBuilder_ == null) {
        result.accessControl_ = accessControl_;
      } else {
        result.accessControl_ = accessControlBuilder_.build();
      }
      result.version_ = version_;
      if (membersBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          members_ = java.util.Collections.unmodifiableList(members_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.members_ = members_;
      } else {
        result.members_ = membersBuilder_.build();
      }
      if (membersPendingProfileKeyBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          membersPendingProfileKey_ = java.util.Collections.unmodifiableList(membersPendingProfileKey_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.membersPendingProfileKey_ = membersPendingProfileKey_;
      } else {
        result.membersPendingProfileKey_ = membersPendingProfileKeyBuilder_.build();
      }
      if (membersPendingAdminApprovalBuilder_ == null) {
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          membersPendingAdminApproval_ = java.util.Collections.unmodifiableList(membersPendingAdminApproval_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.membersPendingAdminApproval_ = membersPendingAdminApproval_;
      } else {
        result.membersPendingAdminApproval_ = membersPendingAdminApprovalBuilder_.build();
      }
      result.inviteLinkPassword_ = inviteLinkPassword_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.signal.storageservice.storage.protos.groups.Group) {
        return mergeFrom((org.signal.storageservice.storage.protos.groups.Group)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.signal.storageservice.storage.protos.groups.Group other) {
      if (other == org.signal.storageservice.storage.protos.groups.Group.getDefaultInstance()) return this;
      if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
        setPublicKey(other.getPublicKey());
      }
      if (other.getTitle() != com.google.protobuf.ByteString.EMPTY) {
        setTitle(other.getTitle());
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        onChanged();
      }
      if (other.getDisappearingMessagesTimer() != com.google.protobuf.ByteString.EMPTY) {
        setDisappearingMessagesTimer(other.getDisappearingMessagesTimer());
      }
      if (other.hasAccessControl()) {
        mergeAccessControl(other.getAccessControl());
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (membersBuilder_ == null) {
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
      } else {
        if (!other.members_.isEmpty()) {
          if (membersBuilder_.isEmpty()) {
            membersBuilder_.dispose();
            membersBuilder_ = null;
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000040);
            membersBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembersFieldBuilder() : null;
          } else {
            membersBuilder_.addAllMessages(other.members_);
          }
        }
      }
      if (membersPendingProfileKeyBuilder_ == null) {
        if (!other.membersPendingProfileKey_.isEmpty()) {
          if (membersPendingProfileKey_.isEmpty()) {
            membersPendingProfileKey_ = other.membersPendingProfileKey_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureMembersPendingProfileKeyIsMutable();
            membersPendingProfileKey_.addAll(other.membersPendingProfileKey_);
          }
          onChanged();
        }
      } else {
        if (!other.membersPendingProfileKey_.isEmpty()) {
          if (membersPendingProfileKeyBuilder_.isEmpty()) {
            membersPendingProfileKeyBuilder_.dispose();
            membersPendingProfileKeyBuilder_ = null;
            membersPendingProfileKey_ = other.membersPendingProfileKey_;
            bitField0_ = (bitField0_ & ~0x00000080);
            membersPendingProfileKeyBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembersPendingProfileKeyFieldBuilder() : null;
          } else {
            membersPendingProfileKeyBuilder_.addAllMessages(other.membersPendingProfileKey_);
          }
        }
      }
      if (membersPendingAdminApprovalBuilder_ == null) {
        if (!other.membersPendingAdminApproval_.isEmpty()) {
          if (membersPendingAdminApproval_.isEmpty()) {
            membersPendingAdminApproval_ = other.membersPendingAdminApproval_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureMembersPendingAdminApprovalIsMutable();
            membersPendingAdminApproval_.addAll(other.membersPendingAdminApproval_);
          }
          onChanged();
        }
      } else {
        if (!other.membersPendingAdminApproval_.isEmpty()) {
          if (membersPendingAdminApprovalBuilder_.isEmpty()) {
            membersPendingAdminApprovalBuilder_.dispose();
            membersPendingAdminApprovalBuilder_ = null;
            membersPendingAdminApproval_ = other.membersPendingAdminApproval_;
            bitField0_ = (bitField0_ & ~0x00000100);
            membersPendingAdminApprovalBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembersPendingAdminApprovalFieldBuilder() : null;
          } else {
            membersPendingAdminApprovalBuilder_.addAllMessages(other.membersPendingAdminApproval_);
          }
        }
      }
      if (other.getInviteLinkPassword() != com.google.protobuf.ByteString.EMPTY) {
        setInviteLinkPassword(other.getInviteLinkPassword());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.signal.storageservice.storage.protos.groups.Group parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.signal.storageservice.storage.protos.groups.Group) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      publicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public Builder clearPublicKey() {

      publicKey_ = getDefaultInstance().getPublicKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString title_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes title = 2;</code>
     */
    public com.google.protobuf.ByteString getTitle() {
      return title_;
    }
    /**
     * <code>optional bytes title = 2;</code>
     */
    public Builder setTitle(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes title = 2;</code>
     */
    public Builder clearTitle() {

      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }

    private java.lang.Object avatar_ = "";
    /**
     * <code>optional string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string avatar = 3;</code>
     */
    public Builder setAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      avatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string avatar = 3;</code>
     */
    public Builder clearAvatar() {

      avatar_ = getDefaultInstance().getAvatar();
      onChanged();
      return this;
    }
    /**
     * <code>optional string avatar = 3;</code>
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      avatar_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString disappearingMessagesTimer_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes disappearingMessagesTimer = 4;</code>
     */
    public com.google.protobuf.ByteString getDisappearingMessagesTimer() {
      return disappearingMessagesTimer_;
    }
    /**
     * <code>optional bytes disappearingMessagesTimer = 4;</code>
     */
    public Builder setDisappearingMessagesTimer(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      disappearingMessagesTimer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes disappearingMessagesTimer = 4;</code>
     */
    public Builder clearDisappearingMessagesTimer() {

      disappearingMessagesTimer_ = getDefaultInstance().getDisappearingMessagesTimer();
      onChanged();
      return this;
    }

    private org.signal.storageservice.storage.protos.groups.AccessControl accessControl_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.AccessControl, org.signal.storageservice.storage.protos.groups.AccessControl.Builder, org.signal.storageservice.storage.protos.groups.AccessControlOrBuilder> accessControlBuilder_;
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    public boolean hasAccessControl() {
      return accessControlBuilder_ != null || accessControl_ != null;
    }
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    public org.signal.storageservice.storage.protos.groups.AccessControl getAccessControl() {
      if (accessControlBuilder_ == null) {
        return accessControl_ == null ? org.signal.storageservice.storage.protos.groups.AccessControl.getDefaultInstance() : accessControl_;
      } else {
        return accessControlBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    public Builder setAccessControl(org.signal.storageservice.storage.protos.groups.AccessControl value) {
      if (accessControlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accessControl_ = value;
        onChanged();
      } else {
        accessControlBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    public Builder setAccessControl(
        org.signal.storageservice.storage.protos.groups.AccessControl.Builder builderForValue) {
      if (accessControlBuilder_ == null) {
        accessControl_ = builderForValue.build();
        onChanged();
      } else {
        accessControlBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    public Builder mergeAccessControl(org.signal.storageservice.storage.protos.groups.AccessControl value) {
      if (accessControlBuilder_ == null) {
        if (accessControl_ != null) {
          accessControl_ =
            org.signal.storageservice.storage.protos.groups.AccessControl.newBuilder(accessControl_).mergeFrom(value).buildPartial();
        } else {
          accessControl_ = value;
        }
        onChanged();
      } else {
        accessControlBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    public Builder clearAccessControl() {
      if (accessControlBuilder_ == null) {
        accessControl_ = null;
        onChanged();
      } else {
        accessControl_ = null;
        accessControlBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    public org.signal.storageservice.storage.protos.groups.AccessControl.Builder getAccessControlBuilder() {

      onChanged();
      return getAccessControlFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    public org.signal.storageservice.storage.protos.groups.AccessControlOrBuilder getAccessControlOrBuilder() {
      if (accessControlBuilder_ != null) {
        return accessControlBuilder_.getMessageOrBuilder();
      } else {
        return accessControl_ == null ?
            org.signal.storageservice.storage.protos.groups.AccessControl.getDefaultInstance() : accessControl_;
      }
    }
    /**
     * <code>optional .signal.AccessControl accessControl = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.AccessControl, org.signal.storageservice.storage.protos.groups.AccessControl.Builder, org.signal.storageservice.storage.protos.groups.AccessControlOrBuilder>
        getAccessControlFieldBuilder() {
      if (accessControlBuilder_ == null) {
        accessControlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.signal.storageservice.storage.protos.groups.AccessControl, org.signal.storageservice.storage.protos.groups.AccessControl.Builder, org.signal.storageservice.storage.protos.groups.AccessControlOrBuilder>(
                getAccessControl(),
                getParentForChildren(),
                isClean());
        accessControl_ = null;
      }
      return accessControlBuilder_;
    }

    private int version_ ;
    /**
     * <code>optional uint32 version = 6;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional uint32 version = 6;</code>
     */
    public Builder setVersion(int value) {

      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 version = 6;</code>
     */
    public Builder clearVersion() {

      version_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.signal.storageservice.storage.protos.groups.Member> members_ =
      java.util.Collections.emptyList();
    private void ensureMembersIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        members_ = new java.util.ArrayList<org.signal.storageservice.storage.protos.groups.Member>(members_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.Member, org.signal.storageservice.storage.protos.groups.Member.Builder, org.signal.storageservice.storage.protos.groups.MemberOrBuilder> membersBuilder_;

    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public java.util.List<org.signal.storageservice.storage.protos.groups.Member> getMembersList() {
      if (membersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(members_);
      } else {
        return membersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public int getMembersCount() {
      if (membersBuilder_ == null) {
        return members_.size();
      } else {
        return membersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public org.signal.storageservice.storage.protos.groups.Member getMembers(int index) {
      if (membersBuilder_ == null) {
        return members_.get(index);
      } else {
        return membersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder setMembers(
        int index, org.signal.storageservice.storage.protos.groups.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
      } else {
        membersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder setMembers(
        int index, org.signal.storageservice.storage.protos.groups.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.set(index, builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder addMembers(org.signal.storageservice.storage.protos.groups.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.add(value);
        onChanged();
      } else {
        membersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder addMembers(
        int index, org.signal.storageservice.storage.protos.groups.Member value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.add(index, value);
        onChanged();
      } else {
        membersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder addMembers(
        org.signal.storageservice.storage.protos.groups.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.add(builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder addMembers(
        int index, org.signal.storageservice.storage.protos.groups.Member.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.add(index, builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder addAllMembers(
        java.lang.Iterable<? extends org.signal.storageservice.storage.protos.groups.Member> values) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
      } else {
        membersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder clearMembers() {
      if (membersBuilder_ == null) {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        membersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public Builder removeMembers(int index) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.remove(index);
        onChanged();
      } else {
        membersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public org.signal.storageservice.storage.protos.groups.Member.Builder getMembersBuilder(
        int index) {
      return getMembersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberOrBuilder getMembersOrBuilder(
        int index) {
      if (membersBuilder_ == null) {
        return members_.get(index);  } else {
        return membersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberOrBuilder>
         getMembersOrBuilderList() {
      if (membersBuilder_ != null) {
        return membersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(members_);
      }
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public org.signal.storageservice.storage.protos.groups.Member.Builder addMembersBuilder() {
      return getMembersFieldBuilder().addBuilder(
          org.signal.storageservice.storage.protos.groups.Member.getDefaultInstance());
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public org.signal.storageservice.storage.protos.groups.Member.Builder addMembersBuilder(
        int index) {
      return getMembersFieldBuilder().addBuilder(
          index, org.signal.storageservice.storage.protos.groups.Member.getDefaultInstance());
    }
    /**
     * <code>repeated .signal.Member members = 7;</code>
     */
    public java.util.List<org.signal.storageservice.storage.protos.groups.Member.Builder>
         getMembersBuilderList() {
      return getMembersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.Member, org.signal.storageservice.storage.protos.groups.Member.Builder, org.signal.storageservice.storage.protos.groups.MemberOrBuilder>
        getMembersFieldBuilder() {
      if (membersBuilder_ == null) {
        membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.signal.storageservice.storage.protos.groups.Member, org.signal.storageservice.storage.protos.groups.Member.Builder, org.signal.storageservice.storage.protos.groups.MemberOrBuilder>(
                members_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        members_ = null;
      }
      return membersBuilder_;
    }

    private java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey> membersPendingProfileKey_ =
      java.util.Collections.emptyList();
    private void ensureMembersPendingProfileKeyIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        membersPendingProfileKey_ = new java.util.ArrayList<org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey>(membersPendingProfileKey_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder> membersPendingProfileKeyBuilder_;

    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey> getMembersPendingProfileKeyList() {
      if (membersPendingProfileKeyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(membersPendingProfileKey_);
      } else {
        return membersPendingProfileKeyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public int getMembersPendingProfileKeyCount() {
      if (membersPendingProfileKeyBuilder_ == null) {
        return membersPendingProfileKey_.size();
      } else {
        return membersPendingProfileKeyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey getMembersPendingProfileKey(int index) {
      if (membersPendingProfileKeyBuilder_ == null) {
        return membersPendingProfileKey_.get(index);
      } else {
        return membersPendingProfileKeyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder setMembersPendingProfileKey(
        int index, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey value) {
      if (membersPendingProfileKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersPendingProfileKeyIsMutable();
        membersPendingProfileKey_.set(index, value);
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder setMembersPendingProfileKey(
        int index, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder builderForValue) {
      if (membersPendingProfileKeyBuilder_ == null) {
        ensureMembersPendingProfileKeyIsMutable();
        membersPendingProfileKey_.set(index, builderForValue.build());
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder addMembersPendingProfileKey(org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey value) {
      if (membersPendingProfileKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersPendingProfileKeyIsMutable();
        membersPendingProfileKey_.add(value);
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder addMembersPendingProfileKey(
        int index, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey value) {
      if (membersPendingProfileKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersPendingProfileKeyIsMutable();
        membersPendingProfileKey_.add(index, value);
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder addMembersPendingProfileKey(
        org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder builderForValue) {
      if (membersPendingProfileKeyBuilder_ == null) {
        ensureMembersPendingProfileKeyIsMutable();
        membersPendingProfileKey_.add(builderForValue.build());
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder addMembersPendingProfileKey(
        int index, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder builderForValue) {
      if (membersPendingProfileKeyBuilder_ == null) {
        ensureMembersPendingProfileKeyIsMutable();
        membersPendingProfileKey_.add(index, builderForValue.build());
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder addAllMembersPendingProfileKey(
        java.lang.Iterable<? extends org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey> values) {
      if (membersPendingProfileKeyBuilder_ == null) {
        ensureMembersPendingProfileKeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, membersPendingProfileKey_);
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder clearMembersPendingProfileKey() {
      if (membersPendingProfileKeyBuilder_ == null) {
        membersPendingProfileKey_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public Builder removeMembersPendingProfileKey(int index) {
      if (membersPendingProfileKeyBuilder_ == null) {
        ensureMembersPendingProfileKeyIsMutable();
        membersPendingProfileKey_.remove(index);
        onChanged();
      } else {
        membersPendingProfileKeyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder getMembersPendingProfileKeyBuilder(
        int index) {
      return getMembersPendingProfileKeyFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder getMembersPendingProfileKeyOrBuilder(
        int index) {
      if (membersPendingProfileKeyBuilder_ == null) {
        return membersPendingProfileKey_.get(index);  } else {
        return membersPendingProfileKeyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder>
         getMembersPendingProfileKeyOrBuilderList() {
      if (membersPendingProfileKeyBuilder_ != null) {
        return membersPendingProfileKeyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(membersPendingProfileKey_);
      }
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder addMembersPendingProfileKeyBuilder() {
      return getMembersPendingProfileKeyFieldBuilder().addBuilder(
          org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.getDefaultInstance());
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder addMembersPendingProfileKeyBuilder(
        int index) {
      return getMembersPendingProfileKeyFieldBuilder().addBuilder(
          index, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.getDefaultInstance());
    }
    /**
     * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
     */
    public java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder>
         getMembersPendingProfileKeyBuilderList() {
      return getMembersPendingProfileKeyFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder>
        getMembersPendingProfileKeyFieldBuilder() {
      if (membersPendingProfileKeyBuilder_ == null) {
        membersPendingProfileKeyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder>(
                membersPendingProfileKey_,
                ((bitField0_ & 0x00000080) == 0x00000080),
                getParentForChildren(),
                isClean());
        membersPendingProfileKey_ = null;
      }
      return membersPendingProfileKeyBuilder_;
    }

    private java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval> membersPendingAdminApproval_ =
      java.util.Collections.emptyList();
    private void ensureMembersPendingAdminApprovalIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        membersPendingAdminApproval_ = new java.util.ArrayList<org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval>(membersPendingAdminApproval_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder> membersPendingAdminApprovalBuilder_;

    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval> getMembersPendingAdminApprovalList() {
      if (membersPendingAdminApprovalBuilder_ == null) {
        return java.util.Collections.unmodifiableList(membersPendingAdminApproval_);
      } else {
        return membersPendingAdminApprovalBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public int getMembersPendingAdminApprovalCount() {
      if (membersPendingAdminApprovalBuilder_ == null) {
        return membersPendingAdminApproval_.size();
      } else {
        return membersPendingAdminApprovalBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval getMembersPendingAdminApproval(int index) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        return membersPendingAdminApproval_.get(index);
      } else {
        return membersPendingAdminApprovalBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder setMembersPendingAdminApproval(
        int index, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval value) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersPendingAdminApprovalIsMutable();
        membersPendingAdminApproval_.set(index, value);
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder setMembersPendingAdminApproval(
        int index, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder builderForValue) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        ensureMembersPendingAdminApprovalIsMutable();
        membersPendingAdminApproval_.set(index, builderForValue.build());
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder addMembersPendingAdminApproval(org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval value) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersPendingAdminApprovalIsMutable();
        membersPendingAdminApproval_.add(value);
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder addMembersPendingAdminApproval(
        int index, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval value) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersPendingAdminApprovalIsMutable();
        membersPendingAdminApproval_.add(index, value);
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder addMembersPendingAdminApproval(
        org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder builderForValue) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        ensureMembersPendingAdminApprovalIsMutable();
        membersPendingAdminApproval_.add(builderForValue.build());
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder addMembersPendingAdminApproval(
        int index, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder builderForValue) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        ensureMembersPendingAdminApprovalIsMutable();
        membersPendingAdminApproval_.add(index, builderForValue.build());
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder addAllMembersPendingAdminApproval(
        java.lang.Iterable<? extends org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval> values) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        ensureMembersPendingAdminApprovalIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, membersPendingAdminApproval_);
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder clearMembersPendingAdminApproval() {
      if (membersPendingAdminApprovalBuilder_ == null) {
        membersPendingAdminApproval_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public Builder removeMembersPendingAdminApproval(int index) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        ensureMembersPendingAdminApprovalIsMutable();
        membersPendingAdminApproval_.remove(index);
        onChanged();
      } else {
        membersPendingAdminApprovalBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder getMembersPendingAdminApprovalBuilder(
        int index) {
      return getMembersPendingAdminApprovalFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder getMembersPendingAdminApprovalOrBuilder(
        int index) {
      if (membersPendingAdminApprovalBuilder_ == null) {
        return membersPendingAdminApproval_.get(index);  } else {
        return membersPendingAdminApprovalBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder>
         getMembersPendingAdminApprovalOrBuilderList() {
      if (membersPendingAdminApprovalBuilder_ != null) {
        return membersPendingAdminApprovalBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(membersPendingAdminApproval_);
      }
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder addMembersPendingAdminApprovalBuilder() {
      return getMembersPendingAdminApprovalFieldBuilder().addBuilder(
          org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.getDefaultInstance());
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder addMembersPendingAdminApprovalBuilder(
        int index) {
      return getMembersPendingAdminApprovalFieldBuilder().addBuilder(
          index, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.getDefaultInstance());
    }
    /**
     * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
     */
    public java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder>
         getMembersPendingAdminApprovalBuilderList() {
      return getMembersPendingAdminApprovalFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder>
        getMembersPendingAdminApprovalFieldBuilder() {
      if (membersPendingAdminApprovalBuilder_ == null) {
        membersPendingAdminApprovalBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder>(
                membersPendingAdminApproval_,
                ((bitField0_ & 0x00000100) == 0x00000100),
                getParentForChildren(),
                isClean());
        membersPendingAdminApproval_ = null;
      }
      return membersPendingAdminApprovalBuilder_;
    }

    private com.google.protobuf.ByteString inviteLinkPassword_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes inviteLinkPassword = 10;</code>
     */
    public com.google.protobuf.ByteString getInviteLinkPassword() {
      return inviteLinkPassword_;
    }
    /**
     * <code>optional bytes inviteLinkPassword = 10;</code>
     */
    public Builder setInviteLinkPassword(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      inviteLinkPassword_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes inviteLinkPassword = 10;</code>
     */
    public Builder clearInviteLinkPassword() {

      inviteLinkPassword_ = getDefaultInstance().getInviteLinkPassword();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:signal.Group)
  }

  // @@protoc_insertion_point(class_scope:signal.Group)
  private static final org.signal.storageservice.storage.protos.groups.Group DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.signal.storageservice.storage.protos.groups.Group();
  }

  public static org.signal.storageservice.storage.protos.groups.Group getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Group>
      PARSER = new com.google.protobuf.AbstractParser<Group>() {
    public Group parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Group(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Group> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Group> getParserForType() {
    return PARSER;
  }

  public org.signal.storageservice.storage.protos.groups.Group getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

