// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

public interface GroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signal.Group)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes publicKey = 1;</code>
   */
  com.google.protobuf.ByteString getPublicKey();

  /**
   * <code>optional bytes title = 2;</code>
   */
  com.google.protobuf.ByteString getTitle();

  /**
   * <code>optional string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>optional string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>optional bytes disappearingMessagesTimer = 4;</code>
   */
  com.google.protobuf.ByteString getDisappearingMessagesTimer();

  /**
   * <code>optional .signal.AccessControl accessControl = 5;</code>
   */
  boolean hasAccessControl();
  /**
   * <code>optional .signal.AccessControl accessControl = 5;</code>
   */
  org.signal.storageservice.storage.protos.groups.AccessControl getAccessControl();
  /**
   * <code>optional .signal.AccessControl accessControl = 5;</code>
   */
  org.signal.storageservice.storage.protos.groups.AccessControlOrBuilder getAccessControlOrBuilder();

  /**
   * <code>optional uint32 version = 6;</code>
   */
  int getVersion();

  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  java.util.List<org.signal.storageservice.storage.protos.groups.Member>
      getMembersList();
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  org.signal.storageservice.storage.protos.groups.Member getMembers(int index);
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  int getMembersCount();
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberOrBuilder>
      getMembersOrBuilderList();
  /**
   * <code>repeated .signal.Member members = 7;</code>
   */
  org.signal.storageservice.storage.protos.groups.MemberOrBuilder getMembersOrBuilder(
      int index);

  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey>
      getMembersPendingProfileKeyList();
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey getMembersPendingProfileKey(int index);
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  int getMembersPendingProfileKeyCount();
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder>
      getMembersPendingProfileKeyOrBuilderList();
  /**
   * <code>repeated .signal.MemberPendingProfileKey membersPendingProfileKey = 8;</code>
   */
  org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder getMembersPendingProfileKeyOrBuilder(
      int index);

  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  java.util.List<org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval>
      getMembersPendingAdminApprovalList();
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval getMembersPendingAdminApproval(int index);
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  int getMembersPendingAdminApprovalCount();
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  java.util.List<? extends org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder>
      getMembersPendingAdminApprovalOrBuilderList();
  /**
   * <code>repeated .signal.MemberPendingAdminApproval membersPendingAdminApproval = 9;</code>
   */
  org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder getMembersPendingAdminApprovalOrBuilder(
      int index);

  /**
   * <code>optional bytes inviteLinkPassword = 10;</code>
   */
  com.google.protobuf.ByteString getInviteLinkPassword();
}
