// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

public interface GroupChangesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signal.GroupChanges)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .signal.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  java.util.List<org.signal.storageservice.storage.protos.groups.GroupChanges.GroupChangeState>
      getGroupChangesList();
  /**
   * <code>repeated .signal.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  org.signal.storageservice.storage.protos.groups.GroupChanges.GroupChangeState getGroupChanges(int index);
  /**
   * <code>repeated .signal.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  int getGroupChangesCount();
  /**
   * <code>repeated .signal.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  java.util.List<? extends org.signal.storageservice.storage.protos.groups.GroupChanges.GroupChangeStateOrBuilder>
      getGroupChangesOrBuilderList();
  /**
   * <code>repeated .signal.GroupChanges.GroupChangeState groupChanges = 1;</code>
   */
  org.signal.storageservice.storage.protos.groups.GroupChanges.GroupChangeStateOrBuilder getGroupChangesOrBuilder(
      int index);
}
