// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

/**
 * Protobuf type {@code signal.Member}
 */
public  final class Member extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:signal.Member)
    MemberOrBuilder {
  // Use Member.newBuilder() to construct.
  private Member(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Member() {
    userId_ = com.google.protobuf.ByteString.EMPTY;
    role_ = 0;
    profileKey_ = com.google.protobuf.ByteString.EMPTY;
    presentation_ = com.google.protobuf.ByteString.EMPTY;
    joinedAtVersion_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Member(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            userId_ = input.readBytes();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            role_ = rawValue;
            break;
          }
          case 26: {

            profileKey_ = input.readBytes();
            break;
          }
          case 34: {

            presentation_ = input.readBytes();
            break;
          }
          case 40: {

            joinedAtVersion_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Member_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Member_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.signal.storageservice.storage.protos.groups.Member.class, org.signal.storageservice.storage.protos.groups.Member.Builder.class);
  }

  /**
   * Protobuf enum {@code signal.Member.Role}
   */
  public enum Role
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>DEFAULT = 1;</code>
     */
    DEFAULT(1),
    /**
     * <code>ADMINISTRATOR = 2;</code>
     */
    ADMINISTRATOR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>DEFAULT = 1;</code>
     */
    public static final int DEFAULT_VALUE = 1;
    /**
     * <code>ADMINISTRATOR = 2;</code>
     */
    public static final int ADMINISTRATOR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Role valueOf(int value) {
      return forNumber(value);
    }

    public static Role forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return DEFAULT;
        case 2: return ADMINISTRATOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Role>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Role> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Role>() {
            public Role findValueByNumber(int number) {
              return Role.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.signal.storageservice.storage.protos.groups.Member.getDescriptor().getEnumTypes().get(0);
    }

    private static final Role[] VALUES = values();

    public static Role valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Role(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:signal.Member.Role)
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString userId_;
  /**
   * <code>optional bytes userId = 1;</code>
   */
  public com.google.protobuf.ByteString getUserId() {
    return userId_;
  }

  public static final int ROLE_FIELD_NUMBER = 2;
  private int role_;
  /**
   * <code>optional .signal.Member.Role role = 2;</code>
   */
  public int getRoleValue() {
    return role_;
  }
  /**
   * <code>optional .signal.Member.Role role = 2;</code>
   */
  public org.signal.storageservice.storage.protos.groups.Member.Role getRole() {
    org.signal.storageservice.storage.protos.groups.Member.Role result = org.signal.storageservice.storage.protos.groups.Member.Role.valueOf(role_);
    return result == null ? org.signal.storageservice.storage.protos.groups.Member.Role.UNRECOGNIZED : result;
  }

  public static final int PROFILEKEY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString profileKey_;
  /**
   * <code>optional bytes profileKey = 3;</code>
   */
  public com.google.protobuf.ByteString getProfileKey() {
    return profileKey_;
  }

  public static final int PRESENTATION_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString presentation_;
  /**
   * <code>optional bytes presentation = 4;</code>
   */
  public com.google.protobuf.ByteString getPresentation() {
    return presentation_;
  }

  public static final int JOINEDATVERSION_FIELD_NUMBER = 5;
  private int joinedAtVersion_;
  /**
   * <code>optional uint32 joinedAtVersion = 5;</code>
   */
  public int getJoinedAtVersion() {
    return joinedAtVersion_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!userId_.isEmpty()) {
      output.writeBytes(1, userId_);
    }
    if (role_ != org.signal.storageservice.storage.protos.groups.Member.Role.UNKNOWN.getNumber()) {
      output.writeEnum(2, role_);
    }
    if (!profileKey_.isEmpty()) {
      output.writeBytes(3, profileKey_);
    }
    if (!presentation_.isEmpty()) {
      output.writeBytes(4, presentation_);
    }
    if (joinedAtVersion_ != 0) {
      output.writeUInt32(5, joinedAtVersion_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!userId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, userId_);
    }
    if (role_ != org.signal.storageservice.storage.protos.groups.Member.Role.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, role_);
    }
    if (!profileKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, profileKey_);
    }
    if (!presentation_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, presentation_);
    }
    if (joinedAtVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, joinedAtVersion_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.signal.storageservice.storage.protos.groups.Member)) {
      return super.equals(obj);
    }
    org.signal.storageservice.storage.protos.groups.Member other = (org.signal.storageservice.storage.protos.groups.Member) obj;

    boolean result = true;
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && role_ == other.role_;
    result = result && getProfileKey()
        .equals(other.getProfileKey());
    result = result && getPresentation()
        .equals(other.getPresentation());
    result = result && (getJoinedAtVersion()
        == other.getJoinedAtVersion());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + role_;
    hash = (37 * hash) + PROFILEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getProfileKey().hashCode();
    hash = (37 * hash) + PRESENTATION_FIELD_NUMBER;
    hash = (53 * hash) + getPresentation().hashCode();
    hash = (37 * hash) + JOINEDATVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getJoinedAtVersion();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.signal.storageservice.storage.protos.groups.Member parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.Member parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.signal.storageservice.storage.protos.groups.Member prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code signal.Member}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:signal.Member)
      org.signal.storageservice.storage.protos.groups.MemberOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Member_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Member_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.signal.storageservice.storage.protos.groups.Member.class, org.signal.storageservice.storage.protos.groups.Member.Builder.class);
    }

    // Construct using org.signal.storageservice.storage.protos.groups.Member.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      userId_ = com.google.protobuf.ByteString.EMPTY;

      role_ = 0;

      profileKey_ = com.google.protobuf.ByteString.EMPTY;

      presentation_ = com.google.protobuf.ByteString.EMPTY;

      joinedAtVersion_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_Member_descriptor;
    }

    public org.signal.storageservice.storage.protos.groups.Member getDefaultInstanceForType() {
      return org.signal.storageservice.storage.protos.groups.Member.getDefaultInstance();
    }

    public org.signal.storageservice.storage.protos.groups.Member build() {
      org.signal.storageservice.storage.protos.groups.Member result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.signal.storageservice.storage.protos.groups.Member buildPartial() {
      org.signal.storageservice.storage.protos.groups.Member result = new org.signal.storageservice.storage.protos.groups.Member(this);
      result.userId_ = userId_;
      result.role_ = role_;
      result.profileKey_ = profileKey_;
      result.presentation_ = presentation_;
      result.joinedAtVersion_ = joinedAtVersion_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.signal.storageservice.storage.protos.groups.Member) {
        return mergeFrom((org.signal.storageservice.storage.protos.groups.Member)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.signal.storageservice.storage.protos.groups.Member other) {
      if (other == org.signal.storageservice.storage.protos.groups.Member.getDefaultInstance()) return this;
      if (other.getUserId() != com.google.protobuf.ByteString.EMPTY) {
        setUserId(other.getUserId());
      }
      if (other.role_ != 0) {
        setRoleValue(other.getRoleValue());
      }
      if (other.getProfileKey() != com.google.protobuf.ByteString.EMPTY) {
        setProfileKey(other.getProfileKey());
      }
      if (other.getPresentation() != com.google.protobuf.ByteString.EMPTY) {
        setPresentation(other.getPresentation());
      }
      if (other.getJoinedAtVersion() != 0) {
        setJoinedAtVersion(other.getJoinedAtVersion());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.signal.storageservice.storage.protos.groups.Member parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.signal.storageservice.storage.protos.groups.Member) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString userId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes userId = 1;</code>
     */
    public com.google.protobuf.ByteString getUserId() {
      return userId_;
    }
    /**
     * <code>optional bytes userId = 1;</code>
     */
    public Builder setUserId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes userId = 1;</code>
     */
    public Builder clearUserId() {

      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }

    private int role_ = 0;
    /**
     * <code>optional .signal.Member.Role role = 2;</code>
     */
    public int getRoleValue() {
      return role_;
    }
    /**
     * <code>optional .signal.Member.Role role = 2;</code>
     */
    public Builder setRoleValue(int value) {
      role_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.Member.Role role = 2;</code>
     */
    public org.signal.storageservice.storage.protos.groups.Member.Role getRole() {
      org.signal.storageservice.storage.protos.groups.Member.Role result = org.signal.storageservice.storage.protos.groups.Member.Role.valueOf(role_);
      return result == null ? org.signal.storageservice.storage.protos.groups.Member.Role.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .signal.Member.Role role = 2;</code>
     */
    public Builder setRole(org.signal.storageservice.storage.protos.groups.Member.Role value) {
      if (value == null) {
        throw new NullPointerException();
      }

      role_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .signal.Member.Role role = 2;</code>
     */
    public Builder clearRole() {

      role_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString profileKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes profileKey = 3;</code>
     */
    public com.google.protobuf.ByteString getProfileKey() {
      return profileKey_;
    }
    /**
     * <code>optional bytes profileKey = 3;</code>
     */
    public Builder setProfileKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      profileKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes profileKey = 3;</code>
     */
    public Builder clearProfileKey() {

      profileKey_ = getDefaultInstance().getProfileKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString presentation_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes presentation = 4;</code>
     */
    public com.google.protobuf.ByteString getPresentation() {
      return presentation_;
    }
    /**
     * <code>optional bytes presentation = 4;</code>
     */
    public Builder setPresentation(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      presentation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes presentation = 4;</code>
     */
    public Builder clearPresentation() {

      presentation_ = getDefaultInstance().getPresentation();
      onChanged();
      return this;
    }

    private int joinedAtVersion_ ;
    /**
     * <code>optional uint32 joinedAtVersion = 5;</code>
     */
    public int getJoinedAtVersion() {
      return joinedAtVersion_;
    }
    /**
     * <code>optional uint32 joinedAtVersion = 5;</code>
     */
    public Builder setJoinedAtVersion(int value) {

      joinedAtVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 joinedAtVersion = 5;</code>
     */
    public Builder clearJoinedAtVersion() {

      joinedAtVersion_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:signal.Member)
  }

  // @@protoc_insertion_point(class_scope:signal.Member)
  private static final org.signal.storageservice.storage.protos.groups.Member DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.signal.storageservice.storage.protos.groups.Member();
  }

  public static org.signal.storageservice.storage.protos.groups.Member getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Member>
      PARSER = new com.google.protobuf.AbstractParser<Member>() {
    public Member parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Member(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Member> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Member> getParserForType() {
    return PARSER;
  }

  public org.signal.storageservice.storage.protos.groups.Member getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

