// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

public interface MemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signal.Member)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes userId = 1;</code>
   */
  com.google.protobuf.ByteString getUserId();

  /**
   * <code>optional .signal.Member.Role role = 2;</code>
   */
  int getRoleValue();
  /**
   * <code>optional .signal.Member.Role role = 2;</code>
   */
  org.signal.storageservice.storage.protos.groups.Member.Role getRole();

  /**
   * <code>optional bytes profileKey = 3;</code>
   */
  com.google.protobuf.ByteString getProfileKey();

  /**
   * <code>optional bytes presentation = 4;</code>
   */
  com.google.protobuf.ByteString getPresentation();

  /**
   * <code>optional uint32 joinedAtVersion = 5;</code>
   */
  int getJoinedAtVersion();
}
