// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

/**
 * Protobuf type {@code signal.MemberPendingProfileKey}
 */
public  final class MemberPendingProfileKey extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:signal.MemberPendingProfileKey)
    MemberPendingProfileKeyOrBuilder {
  // Use MemberPendingProfileKey.newBuilder() to construct.
  private MemberPendingProfileKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MemberPendingProfileKey() {
    addedByUserId_ = com.google.protobuf.ByteString.EMPTY;
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MemberPendingProfileKey(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.signal.storageservice.storage.protos.groups.Member.Builder subBuilder = null;
            if (member_ != null) {
              subBuilder = member_.toBuilder();
            }
            member_ = input.readMessage(org.signal.storageservice.storage.protos.groups.Member.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(member_);
              member_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {

            addedByUserId_ = input.readBytes();
            break;
          }
          case 24: {

            timestamp_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingProfileKey_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingProfileKey_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.class, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder.class);
  }

  public static final int MEMBER_FIELD_NUMBER = 1;
  private org.signal.storageservice.storage.protos.groups.Member member_;
  /**
   * <code>optional .signal.Member member = 1;</code>
   */
  public boolean hasMember() {
    return member_ != null;
  }
  /**
   * <code>optional .signal.Member member = 1;</code>
   */
  public org.signal.storageservice.storage.protos.groups.Member getMember() {
    return member_ == null ? org.signal.storageservice.storage.protos.groups.Member.getDefaultInstance() : member_;
  }
  /**
   * <code>optional .signal.Member member = 1;</code>
   */
  public org.signal.storageservice.storage.protos.groups.MemberOrBuilder getMemberOrBuilder() {
    return getMember();
  }

  public static final int ADDEDBYUSERID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString addedByUserId_;
  /**
   * <code>optional bytes addedByUserId = 2;</code>
   */
  public com.google.protobuf.ByteString getAddedByUserId() {
    return addedByUserId_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <code>optional uint64 timestamp = 3;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (member_ != null) {
      output.writeMessage(1, getMember());
    }
    if (!addedByUserId_.isEmpty()) {
      output.writeBytes(2, addedByUserId_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(3, timestamp_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (member_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMember());
    }
    if (!addedByUserId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, addedByUserId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, timestamp_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey)) {
      return super.equals(obj);
    }
    org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey other = (org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey) obj;

    boolean result = true;
    result = result && (hasMember() == other.hasMember());
    if (hasMember()) {
      result = result && getMember()
          .equals(other.getMember());
    }
    result = result && getAddedByUserId()
        .equals(other.getAddedByUserId());
    result = result && (getTimestamp()
        == other.getTimestamp());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasMember()) {
      hash = (37 * hash) + MEMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMember().hashCode();
    }
    hash = (37 * hash) + ADDEDBYUSERID_FIELD_NUMBER;
    hash = (53 * hash) + getAddedByUserId().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code signal.MemberPendingProfileKey}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:signal.MemberPendingProfileKey)
      org.signal.storageservice.storage.protos.groups.MemberPendingProfileKeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingProfileKey_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingProfileKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.class, org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.Builder.class);
    }

    // Construct using org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (memberBuilder_ == null) {
        member_ = null;
      } else {
        member_ = null;
        memberBuilder_ = null;
      }
      addedByUserId_ = com.google.protobuf.ByteString.EMPTY;

      timestamp_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingProfileKey_descriptor;
    }

    public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey getDefaultInstanceForType() {
      return org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.getDefaultInstance();
    }

    public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey build() {
      org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey buildPartial() {
      org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey result = new org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey(this);
      if (memberBuilder_ == null) {
        result.member_ = member_;
      } else {
        result.member_ = memberBuilder_.build();
      }
      result.addedByUserId_ = addedByUserId_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey) {
        return mergeFrom((org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey other) {
      if (other == org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey.getDefaultInstance()) return this;
      if (other.hasMember()) {
        mergeMember(other.getMember());
      }
      if (other.getAddedByUserId() != com.google.protobuf.ByteString.EMPTY) {
        setAddedByUserId(other.getAddedByUserId());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.signal.storageservice.storage.protos.groups.Member member_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.Member, org.signal.storageservice.storage.protos.groups.Member.Builder, org.signal.storageservice.storage.protos.groups.MemberOrBuilder> memberBuilder_;
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    public boolean hasMember() {
      return memberBuilder_ != null || member_ != null;
    }
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    public org.signal.storageservice.storage.protos.groups.Member getMember() {
      if (memberBuilder_ == null) {
        return member_ == null ? org.signal.storageservice.storage.protos.groups.Member.getDefaultInstance() : member_;
      } else {
        return memberBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    public Builder setMember(org.signal.storageservice.storage.protos.groups.Member value) {
      if (memberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        member_ = value;
        onChanged();
      } else {
        memberBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    public Builder setMember(
        org.signal.storageservice.storage.protos.groups.Member.Builder builderForValue) {
      if (memberBuilder_ == null) {
        member_ = builderForValue.build();
        onChanged();
      } else {
        memberBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    public Builder mergeMember(org.signal.storageservice.storage.protos.groups.Member value) {
      if (memberBuilder_ == null) {
        if (member_ != null) {
          member_ =
            org.signal.storageservice.storage.protos.groups.Member.newBuilder(member_).mergeFrom(value).buildPartial();
        } else {
          member_ = value;
        }
        onChanged();
      } else {
        memberBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    public Builder clearMember() {
      if (memberBuilder_ == null) {
        member_ = null;
        onChanged();
      } else {
        member_ = null;
        memberBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    public org.signal.storageservice.storage.protos.groups.Member.Builder getMemberBuilder() {

      onChanged();
      return getMemberFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    public org.signal.storageservice.storage.protos.groups.MemberOrBuilder getMemberOrBuilder() {
      if (memberBuilder_ != null) {
        return memberBuilder_.getMessageOrBuilder();
      } else {
        return member_ == null ?
            org.signal.storageservice.storage.protos.groups.Member.getDefaultInstance() : member_;
      }
    }
    /**
     * <code>optional .signal.Member member = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.signal.storageservice.storage.protos.groups.Member, org.signal.storageservice.storage.protos.groups.Member.Builder, org.signal.storageservice.storage.protos.groups.MemberOrBuilder>
        getMemberFieldBuilder() {
      if (memberBuilder_ == null) {
        memberBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.signal.storageservice.storage.protos.groups.Member, org.signal.storageservice.storage.protos.groups.Member.Builder, org.signal.storageservice.storage.protos.groups.MemberOrBuilder>(
                getMember(),
                getParentForChildren(),
                isClean());
        member_ = null;
      }
      return memberBuilder_;
    }

    private com.google.protobuf.ByteString addedByUserId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes addedByUserId = 2;</code>
     */
    public com.google.protobuf.ByteString getAddedByUserId() {
      return addedByUserId_;
    }
    /**
     * <code>optional bytes addedByUserId = 2;</code>
     */
    public Builder setAddedByUserId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      addedByUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes addedByUserId = 2;</code>
     */
    public Builder clearAddedByUserId() {

      addedByUserId_ = getDefaultInstance().getAddedByUserId();
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>optional uint64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional uint64 timestamp = 3;</code>
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 timestamp = 3;</code>
     */
    public Builder clearTimestamp() {

      timestamp_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:signal.MemberPendingProfileKey)
  }

  // @@protoc_insertion_point(class_scope:signal.MemberPendingProfileKey)
  private static final org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey();
  }

  public static org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MemberPendingProfileKey>
      PARSER = new com.google.protobuf.AbstractParser<MemberPendingProfileKey>() {
    public MemberPendingProfileKey parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MemberPendingProfileKey(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MemberPendingProfileKey> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MemberPendingProfileKey> getParserForType() {
    return PARSER;
  }

  public org.signal.storageservice.storage.protos.groups.MemberPendingProfileKey getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

