// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

public interface MemberPendingProfileKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signal.MemberPendingProfileKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .signal.Member member = 1;</code>
   */
  boolean hasMember();
  /**
   * <code>optional .signal.Member member = 1;</code>
   */
  org.signal.storageservice.storage.protos.groups.Member getMember();
  /**
   * <code>optional .signal.Member member = 1;</code>
   */
  org.signal.storageservice.storage.protos.groups.MemberOrBuilder getMemberOrBuilder();

  /**
   * <code>optional bytes addedByUserId = 2;</code>
   */
  com.google.protobuf.ByteString getAddedByUserId();

  /**
   * <code>optional uint64 timestamp = 3;</code>
   */
  long getTimestamp();
}
