// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

public interface MemberPendingAdminApprovalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:signal.MemberPendingAdminApproval)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes userId = 1;</code>
   */
  com.google.protobuf.ByteString getUserId();

  /**
   * <code>optional bytes profileKey = 2;</code>
   */
  com.google.protobuf.ByteString getProfileKey();

  /**
   * <code>optional bytes presentation = 3;</code>
   */
  com.google.protobuf.ByteString getPresentation();

  /**
   * <code>optional uint64 timestamp = 4;</code>
   */
  long getTimestamp();
}
