// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Groups.proto

package org.signal.storageservice.storage.protos.groups;

/**
 * Protobuf type {@code signal.MemberPendingAdminApproval}
 */
public  final class MemberPendingAdminApproval extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:signal.MemberPendingAdminApproval)
    MemberPendingAdminApprovalOrBuilder {
  // Use MemberPendingAdminApproval.newBuilder() to construct.
  private MemberPendingAdminApproval(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MemberPendingAdminApproval() {
    userId_ = com.google.protobuf.ByteString.EMPTY;
    profileKey_ = com.google.protobuf.ByteString.EMPTY;
    presentation_ = com.google.protobuf.ByteString.EMPTY;
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MemberPendingAdminApproval(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            userId_ = input.readBytes();
            break;
          }
          case 18: {

            profileKey_ = input.readBytes();
            break;
          }
          case 26: {

            presentation_ = input.readBytes();
            break;
          }
          case 32: {

            timestamp_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingAdminApproval_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingAdminApproval_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.class, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString userId_;
  /**
   * <code>optional bytes userId = 1;</code>
   */
  public com.google.protobuf.ByteString getUserId() {
    return userId_;
  }

  public static final int PROFILEKEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString profileKey_;
  /**
   * <code>optional bytes profileKey = 2;</code>
   */
  public com.google.protobuf.ByteString getProfileKey() {
    return profileKey_;
  }

  public static final int PRESENTATION_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString presentation_;
  /**
   * <code>optional bytes presentation = 3;</code>
   */
  public com.google.protobuf.ByteString getPresentation() {
    return presentation_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_;
  /**
   * <code>optional uint64 timestamp = 4;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!userId_.isEmpty()) {
      output.writeBytes(1, userId_);
    }
    if (!profileKey_.isEmpty()) {
      output.writeBytes(2, profileKey_);
    }
    if (!presentation_.isEmpty()) {
      output.writeBytes(3, presentation_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(4, timestamp_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!userId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, userId_);
    }
    if (!profileKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, profileKey_);
    }
    if (!presentation_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, presentation_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, timestamp_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval)) {
      return super.equals(obj);
    }
    org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval other = (org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval) obj;

    boolean result = true;
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && getProfileKey()
        .equals(other.getProfileKey());
    result = result && getPresentation()
        .equals(other.getPresentation());
    result = result && (getTimestamp()
        == other.getTimestamp());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + PROFILEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getProfileKey().hashCode();
    hash = (37 * hash) + PRESENTATION_FIELD_NUMBER;
    hash = (53 * hash) + getPresentation().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code signal.MemberPendingAdminApproval}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:signal.MemberPendingAdminApproval)
      org.signal.storageservice.storage.protos.groups.MemberPendingAdminApprovalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingAdminApproval_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingAdminApproval_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.class, org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.Builder.class);
    }

    // Construct using org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      userId_ = com.google.protobuf.ByteString.EMPTY;

      profileKey_ = com.google.protobuf.ByteString.EMPTY;

      presentation_ = com.google.protobuf.ByteString.EMPTY;

      timestamp_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.signal.storageservice.storage.protos.groups.GroupProtos.internal_static_signal_MemberPendingAdminApproval_descriptor;
    }

    public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval getDefaultInstanceForType() {
      return org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.getDefaultInstance();
    }

    public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval build() {
      org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval buildPartial() {
      org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval result = new org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval(this);
      result.userId_ = userId_;
      result.profileKey_ = profileKey_;
      result.presentation_ = presentation_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval) {
        return mergeFrom((org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval other) {
      if (other == org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval.getDefaultInstance()) return this;
      if (other.getUserId() != com.google.protobuf.ByteString.EMPTY) {
        setUserId(other.getUserId());
      }
      if (other.getProfileKey() != com.google.protobuf.ByteString.EMPTY) {
        setProfileKey(other.getProfileKey());
      }
      if (other.getPresentation() != com.google.protobuf.ByteString.EMPTY) {
        setPresentation(other.getPresentation());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString userId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes userId = 1;</code>
     */
    public com.google.protobuf.ByteString getUserId() {
      return userId_;
    }
    /**
     * <code>optional bytes userId = 1;</code>
     */
    public Builder setUserId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes userId = 1;</code>
     */
    public Builder clearUserId() {

      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString profileKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes profileKey = 2;</code>
     */
    public com.google.protobuf.ByteString getProfileKey() {
      return profileKey_;
    }
    /**
     * <code>optional bytes profileKey = 2;</code>
     */
    public Builder setProfileKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      profileKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes profileKey = 2;</code>
     */
    public Builder clearProfileKey() {

      profileKey_ = getDefaultInstance().getProfileKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString presentation_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes presentation = 3;</code>
     */
    public com.google.protobuf.ByteString getPresentation() {
      return presentation_;
    }
    /**
     * <code>optional bytes presentation = 3;</code>
     */
    public Builder setPresentation(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      presentation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes presentation = 3;</code>
     */
    public Builder clearPresentation() {

      presentation_ = getDefaultInstance().getPresentation();
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>optional uint64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional uint64 timestamp = 4;</code>
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 timestamp = 4;</code>
     */
    public Builder clearTimestamp() {

      timestamp_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:signal.MemberPendingAdminApproval)
  }

  // @@protoc_insertion_point(class_scope:signal.MemberPendingAdminApproval)
  private static final org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval();
  }

  public static org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MemberPendingAdminApproval>
      PARSER = new com.google.protobuf.AbstractParser<MemberPendingAdminApproval>() {
    public MemberPendingAdminApproval parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MemberPendingAdminApproval(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MemberPendingAdminApproval> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MemberPendingAdminApproval> getParserForType() {
    return PARSER;
  }

  public org.signal.storageservice.storage.protos.groups.MemberPendingAdminApproval getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

